# coding: utf-8

"""
    SimpleBilly API

    Simplebilly API - Bookkeeping, CRM, ERP. Multi-tenant API: a tenant is isolated and routed by subdomain (or a configured custom domain) under the base domain.  ## Rate limiting All endpoints are rate-limited per client IP: **100 requests per minute** on API routes and **5 requests per minute** on authentication routes. Exceeding a limit returns `429 Too Many Requests`; the window resets after 60 seconds.

    The version of the OpenAPI document: 0.1.0
    Contact: support@simplebilly.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from simplebilly_api.api.down_payment_invoice_api import DownPaymentInvoiceApi


class TestDownPaymentInvoiceApi(unittest.TestCase):
    """DownPaymentInvoiceApi unit test stubs"""

    def setUp(self) -> None:
        self.api = DownPaymentInvoiceApi()

    def tearDown(self) -> None:
        pass

    def test_download_down_payment_invoice_pdf(self) -> None:
        """Test case for download_down_payment_invoice_pdf

        """
        pass

    def test_get_down_payment_invoice(self) -> None:
        """Test case for get_down_payment_invoice

        """
        pass

    def test_list_down_payment_invoices(self) -> None:
        """Test case for list_down_payment_invoices

        """
        pass


if __name__ == '__main__':
    unittest.main()
