# coding: utf-8

"""
    SimpleBilly API

    Simplebilly API - Bookkeeping, CRM, ERP. Multi-tenant API: a tenant is isolated and routed by subdomain (or a configured custom domain) under the base domain.  ## Rate limiting All endpoints are rate-limited per client IP: **100 requests per minute** on API routes and **5 requests per minute** on authentication routes. Exceeding a limit returns `429 Too Many Requests`; the window resets after 60 seconds.

    The version of the OpenAPI document: 0.1.0
    Contact: support@simplebilly.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from simplebilly_api.api.goods_receipt_api import GoodsReceiptApi


class TestGoodsReceiptApi(unittest.TestCase):
    """GoodsReceiptApi unit test stubs"""

    def setUp(self) -> None:
        self.api = GoodsReceiptApi()

    def tearDown(self) -> None:
        pass

    def test_create_goods_receipt(self) -> None:
        """Test case for create_goods_receipt

        """
        pass

    def test_delete_goods_receipt(self) -> None:
        """Test case for delete_goods_receipt

        """
        pass

    def test_get_goods_receipt(self) -> None:
        """Test case for get_goods_receipt

        """
        pass

    def test_list_goods_receipts(self) -> None:
        """Test case for list_goods_receipts

        """
        pass


if __name__ == '__main__':
    unittest.main()
