# coding: utf-8

"""
    SimpleBilly API

    Simplebilly API - Bookkeeping, CRM, ERP. Multi-tenant API: a tenant is isolated and routed by subdomain (or a configured custom domain) under the base domain.  ## Rate limiting All endpoints are rate-limited per client IP: **100 requests per minute** on API routes and **5 requests per minute** on authentication routes. Exceeding a limit returns `429 Too Many Requests`; the window resets after 60 seconds.

    The version of the OpenAPI document: 0.1.0
    Contact: support@simplebilly.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from simplebilly_api.models.return_logistics_queue_item import ReturnLogisticsQueueItem

class TestReturnLogisticsQueueItem(unittest.TestCase):
    """ReturnLogisticsQueueItem unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> ReturnLogisticsQueueItem:
        """Test ReturnLogisticsQueueItem
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `ReturnLogisticsQueueItem`
        """
        model = ReturnLogisticsQueueItem()
        if include_optional:
            return ReturnLogisticsQueueItem(
                age_days = 56,
                created_at = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'),
                customer_name = '',
                line_items = None,
                order_number = '',
                return_number = '',
                return_order_id = '',
                status = '',
                warehouse_id = ''
            )
        else:
            return ReturnLogisticsQueueItem(
                age_days = 56,
                created_at = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'),
                line_items = None,
                return_number = '',
                return_order_id = '',
                status = '',
        )
        """

    def testReturnLogisticsQueueItem(self):
        """Test ReturnLogisticsQueueItem"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
