# coding: utf-8

"""
    SimpleBilly API

    Simplebilly API - Bookkeeping, CRM, ERP. Multi-tenant API: a tenant is isolated and routed by subdomain (or a configured custom domain) under the base domain.  ## Rate limiting All endpoints are rate-limited per client IP: **100 requests per minute** on API routes and **5 requests per minute** on authentication routes. Exceeding a limit returns `429 Too Many Requests`; the window resets after 60 seconds.

    The version of the OpenAPI document: 0.1.0
    Contact: support@simplebilly.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from simplebilly_api.api.employee_api import EmployeeApi


class TestEmployeeApi(unittest.TestCase):
    """EmployeeApi unit test stubs"""

    def setUp(self) -> None:
        self.api = EmployeeApi()

    def tearDown(self) -> None:
        pass

    def test_create_employee(self) -> None:
        """Test case for create_employee

        """
        pass

    def test_delete_employee(self) -> None:
        """Test case for delete_employee

        """
        pass

    def test_employee_restore(self) -> None:
        """Test case for employee_restore

        """
        pass

    def test_get_employee(self) -> None:
        """Test case for get_employee

        """
        pass

    def test_get_employee_payroll_summary(self) -> None:
        """Test case for get_employee_payroll_summary

        """
        pass

    def test_get_employees(self) -> None:
        """Test case for get_employees

        """
        pass

    def test_update_employee(self) -> None:
        """Test case for update_employee

        """
        pass


if __name__ == '__main__':
    unittest.main()
