# coding: utf-8

"""
    SimpleBilly API

    Simplebilly API - Bookkeeping, CRM, ERP. Multi-tenant API: a tenant is isolated and routed by subdomain (or a configured custom domain) under the base domain.  ## Rate limiting All endpoints are rate-limited per client IP: **100 requests per minute** on API routes and **5 requests per minute** on authentication routes. Exceeding a limit returns `429 Too Many Requests`; the window resets after 60 seconds.

    The version of the OpenAPI document: 0.1.0
    Contact: support@simplebilly.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from simplebilly_api.models.konzern_status import KonzernStatus

class TestKonzernStatus(unittest.TestCase):
    """KonzernStatus unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> KonzernStatus:
        """Test KonzernStatus
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `KonzernStatus`
        """
        model = KonzernStatus()
        if include_optional:
            return KonzernStatus(
                groessenbefreit = True,
                kapitalmarktorientiert = True,
                konzernabschlusspflicht = True,
                missing_group_figures = True,
                mutterunternehmen = True,
                parent_name = '',
                parent_situs = '',
                participations = [
                    simplebilly_api.models.konzern_beteiligung.KonzernBeteiligung(
                        company_name = '', 
                        control_basis = [
                            ''
                            ], 
                        controlled = True, 
                        ownership_pct = '', )
                    ],
                thresholds = simplebilly_api.models.konzern_thresholds.KonzernThresholds(
                    bilanzsumme = '', 
                    mitarbeiter = 56, 
                    netto_umsatz = '', ),
                year = 56,
                zwischenholding_befreit = True,
                zwischenholding_hinweis = ''
            )
        else:
            return KonzernStatus(
                groessenbefreit = True,
                kapitalmarktorientiert = True,
                konzernabschlusspflicht = True,
                missing_group_figures = True,
                mutterunternehmen = True,
                participations = [
                    simplebilly_api.models.konzern_beteiligung.KonzernBeteiligung(
                        company_name = '', 
                        control_basis = [
                            ''
                            ], 
                        controlled = True, 
                        ownership_pct = '', )
                    ],
                thresholds = simplebilly_api.models.konzern_thresholds.KonzernThresholds(
                    bilanzsumme = '', 
                    mitarbeiter = 56, 
                    netto_umsatz = '', ),
                year = 56,
                zwischenholding_befreit = True,
        )
        """

    def testKonzernStatus(self):
        """Test KonzernStatus"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
