# coding: utf-8

"""
    SimpleBilly API

    Simplebilly API - Bookkeeping, CRM, ERP. Multi-tenant API: a tenant is isolated and routed by subdomain (or a configured custom domain) under the base domain.  ## Rate limiting All endpoints are rate-limited per client IP: **100 requests per minute** on API routes and **5 requests per minute** on authentication routes. Exceeding a limit returns `429 Too Many Requests`; the window resets after 60 seconds.

    The version of the OpenAPI document: 0.1.0
    Contact: support@simplebilly.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from simplebilly_api.api.budgets_api import BudgetsApi


class TestBudgetsApi(unittest.TestCase):
    """BudgetsApi unit test stubs"""

    def setUp(self) -> None:
        self.api = BudgetsApi()

    def tearDown(self) -> None:
        pass

    def test_budgets_api(self) -> None:
        """Test case for budgets_api

        """
        pass

    def test_upsert_budget_goal_api(self) -> None:
        """Test case for upsert_budget_goal_api

        """
        pass


if __name__ == '__main__':
    unittest.main()
