# coding: utf-8

"""
    SimpleBilly API

    Simplebilly API - Bookkeeping, CRM, ERP. Multi-tenant API: a tenant is isolated and routed by subdomain (or a configured custom domain) under the base domain.  ## Rate limiting All endpoints are rate-limited per client IP: **100 requests per minute** on API routes and **5 requests per minute** on authentication routes. Exceeding a limit returns `429 Too Many Requests`; the window resets after 60 seconds.

    The version of the OpenAPI document: 0.1.0
    Contact: support@simplebilly.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from simplebilly_api.models.supplier_invoice_status_update import SupplierInvoiceStatusUpdate

class TestSupplierInvoiceStatusUpdate(unittest.TestCase):
    """SupplierInvoiceStatusUpdate unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> SupplierInvoiceStatusUpdate:
        """Test SupplierInvoiceStatusUpdate
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `SupplierInvoiceStatusUpdate`
        """
        model = SupplierInvoiceStatusUpdate()
        if include_optional:
            return SupplierInvoiceStatusUpdate(
                status = ''
            )
        else:
            return SupplierInvoiceStatusUpdate(
                status = '',
        )
        """

    def testSupplierInvoiceStatusUpdate(self):
        """Test SupplierInvoiceStatusUpdate"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
