# coding: utf-8

"""
    SimpleBilly API

    Simplebilly API - Bookkeeping, CRM, ERP. Multi-tenant API: a tenant is isolated and routed by subdomain (or a configured custom domain) under the base domain.  ## Rate limiting All endpoints are rate-limited per client IP: **100 requests per minute** on API routes and **5 requests per minute** on authentication routes. Exceeding a limit returns `429 Too Many Requests`; the window resets after 60 seconds.

    The version of the OpenAPI document: 0.1.0
    Contact: support@simplebilly.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from simplebilly_api.api.purchase_order_api import PurchaseOrderApi


class TestPurchaseOrderApi(unittest.TestCase):
    """PurchaseOrderApi unit test stubs"""

    def setUp(self) -> None:
        self.api = PurchaseOrderApi()

    def tearDown(self) -> None:
        pass

    def test_create_purchase_order(self) -> None:
        """Test case for create_purchase_order

        """
        pass

    def test_delete_purchase_order(self) -> None:
        """Test case for delete_purchase_order

        """
        pass

    def test_get_purchase_order(self) -> None:
        """Test case for get_purchase_order

        """
        pass

    def test_list_purchase_orders(self) -> None:
        """Test case for list_purchase_orders

        """
        pass

    def test_match_invoice(self) -> None:
        """Test case for match_invoice

        3-way invoice check (Rechnungsprüfung): compares the purchase order line items, the quantities received via goods receipts, and the supplier invoice line items, reporting quantity and price variances per product.
        """
        pass

    def test_update_purchase_order(self) -> None:
        """Test case for update_purchase_order

        """
        pass

    def test_update_purchase_order_status(self) -> None:
        """Test case for update_purchase_order_status

        """
        pass


if __name__ == '__main__':
    unittest.main()
