# coding: utf-8

"""
    SimpleBilly API

    Simplebilly API - Bookkeeping, CRM, ERP. Multi-tenant API: a tenant is isolated and routed by subdomain (or a configured custom domain) under the base domain.  ## Rate limiting All endpoints are rate-limited per client IP: **100 requests per minute** on API routes and **5 requests per minute** on authentication routes. Exceeding a limit returns `429 Too Many Requests`; the window resets after 60 seconds.

    The version of the OpenAPI document: 0.1.0
    Contact: support@simplebilly.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from simplebilly_api.api.emissions_api import EmissionsApi


class TestEmissionsApi(unittest.TestCase):
    """EmissionsApi unit test stubs"""

    def setUp(self) -> None:
        self.api = EmissionsApi()

    def tearDown(self) -> None:
        pass

    def test_create_emission_entry_api(self) -> None:
        """Test case for create_emission_entry_api

        """
        pass

    def test_create_emission_target_api(self) -> None:
        """Test case for create_emission_target_api

        """
        pass

    def test_delete_emission_entry_api(self) -> None:
        """Test case for delete_emission_entry_api

        """
        pass

    def test_delete_emission_target_api(self) -> None:
        """Test case for delete_emission_target_api

        """
        pass

    def test_emissions_entries_api(self) -> None:
        """Test case for emissions_entries_api

        """
        pass

    def test_emissions_export_api(self) -> None:
        """Test case for emissions_export_api

        """
        pass

    def test_emissions_factors_api(self) -> None:
        """Test case for emissions_factors_api

        """
        pass

    def test_emissions_report_api(self) -> None:
        """Test case for emissions_report_api

        """
        pass

    def test_emissions_targets_api(self) -> None:
        """Test case for emissions_targets_api

        """
        pass


if __name__ == '__main__':
    unittest.main()
