# coding: utf-8

"""
    SimpleBilly API

    Simplebilly API - Bookkeeping, CRM, ERP. Multi-tenant API: a tenant is isolated and routed by subdomain (or a configured custom domain) under the base domain.  ## Rate limiting All endpoints are rate-limited per client IP: **100 requests per minute** on API routes and **5 requests per minute** on authentication routes. Exceeding a limit returns `429 Too Many Requests`; the window resets after 60 seconds.

    The version of the OpenAPI document: 0.1.0
    Contact: support@simplebilly.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from simplebilly_api.models.euer_detail_ergebnis import EuerDetailErgebnis

class TestEuerDetailErgebnis(unittest.TestCase):
    """EuerDetailErgebnis unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> EuerDetailErgebnis:
        """Test EuerDetailErgebnis
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `EuerDetailErgebnis`
        """
        model = EuerDetailErgebnis()
        if include_optional:
            return EuerDetailErgebnis(
                jahr = 56,
                zeilen = [
                    simplebilly_api.models.euer_zeile_detail.EuerZeileDetail(
                        abschnitt = '', 
                        betrag_gesamt = '', 
                        bezeichnung = '', 
                        kategorien = [
                            simplebilly_api.models.euer_kat_summe.EuerKatSumme(
                                betrag = '', 
                                name = '', )
                            ], 
                        zeile = 56, )
                    ]
            )
        else:
            return EuerDetailErgebnis(
                jahr = 56,
                zeilen = [
                    simplebilly_api.models.euer_zeile_detail.EuerZeileDetail(
                        abschnitt = '', 
                        betrag_gesamt = '', 
                        bezeichnung = '', 
                        kategorien = [
                            simplebilly_api.models.euer_kat_summe.EuerKatSumme(
                                betrag = '', 
                                name = '', )
                            ], 
                        zeile = 56, )
                    ],
        )
        """

    def testEuerDetailErgebnis(self):
        """Test EuerDetailErgebnis"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
