# coding: utf-8

"""
    SimpleBilly API

    Simplebilly API - Bookkeeping, CRM, ERP. Multi-tenant API: a tenant is isolated and routed by subdomain (or a configured custom domain) under the base domain.  ## Rate limiting All endpoints are rate-limited per client IP: **100 requests per minute** on API routes and **5 requests per minute** on authentication routes. Exceeding a limit returns `429 Too Many Requests`; the window resets after 60 seconds.

    The version of the OpenAPI document: 0.1.0
    Contact: support@simplebilly.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from datetime import date
from pydantic import BaseModel, ConfigDict, Field, StrictStr
from typing import Any, ClassVar, Dict, List, Optional
from simplebilly_api.models.activity_status import ActivityStatus
from simplebilly_api.models.activity_type import ActivityType
from typing import Optional, Set
from typing_extensions import Self
from pydantic_core import to_jsonable_python

class ActivityUpdate(BaseModel):
    """
    ActivityUpdate
    """ # noqa: E501
    activity_type: Optional[ActivityType] = Field(default=None, description="One of: call | email | meeting | task | note", alias="activityType")
    assigned_to: Optional[StrictStr] = Field(default=None, description="User responsible (`employee.employee_id`).", alias="assignedTo")
    contact_id: Optional[StrictStr] = Field(default=None, description="Contact this activity belongs to (`contact.contact_id`). References the contact entity.", alias="contactId")
    description: Optional[StrictStr] = None
    due_date: Optional[date] = Field(default=None, description="Follow-up / Wiedervorlage date. Open activities with a due date in the past are overdue.", alias="dueDate")
    reminder_date: Optional[date] = Field(default=None, description="When to remind about the follow-up.", alias="reminderDate")
    status: Optional[ActivityStatus] = Field(default=None, description="One of: open | done | cancelled")
    subject: Optional[StrictStr] = Field(default=None, description="Short subject line.")
    __properties: ClassVar[List[str]] = ["activityType", "assignedTo", "contactId", "description", "dueDate", "reminderDate", "status", "subject"]

    model_config = ConfigDict(
        validate_by_name=True,
        validate_by_alias=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        return json.dumps(to_jsonable_python(self.to_dict()))

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of ActivityUpdate from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # set to None if activity_type (nullable) is None
        # and model_fields_set contains the field
        if self.activity_type is None and "activity_type" in self.model_fields_set:
            _dict['activityType'] = None

        # set to None if assigned_to (nullable) is None
        # and model_fields_set contains the field
        if self.assigned_to is None and "assigned_to" in self.model_fields_set:
            _dict['assignedTo'] = None

        # set to None if contact_id (nullable) is None
        # and model_fields_set contains the field
        if self.contact_id is None and "contact_id" in self.model_fields_set:
            _dict['contactId'] = None

        # set to None if description (nullable) is None
        # and model_fields_set contains the field
        if self.description is None and "description" in self.model_fields_set:
            _dict['description'] = None

        # set to None if due_date (nullable) is None
        # and model_fields_set contains the field
        if self.due_date is None and "due_date" in self.model_fields_set:
            _dict['dueDate'] = None

        # set to None if reminder_date (nullable) is None
        # and model_fields_set contains the field
        if self.reminder_date is None and "reminder_date" in self.model_fields_set:
            _dict['reminderDate'] = None

        # set to None if status (nullable) is None
        # and model_fields_set contains the field
        if self.status is None and "status" in self.model_fields_set:
            _dict['status'] = None

        # set to None if subject (nullable) is None
        # and model_fields_set contains the field
        if self.subject is None and "subject" in self.model_fields_set:
            _dict['subject'] = None

        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of ActivityUpdate from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "activityType": obj.get("activityType"),
            "assignedTo": obj.get("assignedTo"),
            "contactId": obj.get("contactId"),
            "description": obj.get("description"),
            "dueDate": obj.get("dueDate"),
            "reminderDate": obj.get("reminderDate"),
            "status": obj.get("status"),
            "subject": obj.get("subject")
        })
        return _obj


