# coding: utf-8

"""
    SimpleBilly API

    Simplebilly API - Bookkeeping, CRM, ERP. Multi-tenant API: a tenant is isolated and routed by subdomain (or a configured custom domain) under the base domain.  ## Rate limiting All endpoints are rate-limited per client IP: **100 requests per minute** on API routes and **5 requests per minute** on authentication routes. Exceeding a limit returns `429 Too Many Requests`; the window resets after 60 seconds.

    The version of the OpenAPI document: 0.1.0
    Contact: support@simplebilly.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict, StrictBool, StrictInt, StrictStr
from typing import Any, ClassVar, Dict, List, Optional
from typing import Optional, Set
from typing_extensions import Self
from pydantic_core import to_jsonable_python

class Contact(BaseModel):
    """
    Contact
    """ # noqa: E501
    account_holder: Optional[StrictStr] = None
    acquisition_cost: Optional[StrictStr] = None
    address_supplement: Optional[StrictStr] = None
    attention: Optional[StrictStr] = None
    bank_name: Optional[StrictStr] = None
    bic: Optional[StrictStr] = None
    buyer_reference: Optional[StrictStr] = None
    category: Optional[StrictStr] = None
    certificate_authority: Optional[StrictStr] = None
    certificate_number: Optional[StrictStr] = None
    certificate_paragraph: Optional[StrictStr] = None
    certificate_valid_until: Optional[StrictStr] = None
    city: Optional[StrictStr] = None
    company_name: Optional[StrictStr] = None
    contact_id: StrictStr
    contact_persons: Optional[Any]
    contact_type: StrictStr
    country: Optional[StrictStr] = None
    created_at: StrictStr
    credit_limit: Optional[StrictStr] = None
    creditor_account_skr03: Optional[StrictStr] = None
    creditor_account_skr04: Optional[StrictStr] = None
    currency: Optional[StrictStr] = None
    customer_number: Optional[StrictStr] = None
    debitor_account_skr03: Optional[StrictStr] = None
    debitor_account_skr04: Optional[StrictStr] = None
    default_debitor_number: Optional[StrictStr] = None
    delivery_block: Optional[StrictBool] = None
    department: Optional[StrictStr] = None
    discount_days: Optional[StrictInt] = None
    discount_percentage: Optional[StrictStr] = None
    donation_receipt_eligible: Optional[StrictBool] = None
    email: Optional[StrictStr] = None
    external_id: Optional[StrictStr] = None
    fax: Optional[StrictStr] = None
    iban: Optional[StrictStr] = None
    industry: Optional[StrictStr] = None
    is_active: Optional[StrictBool] = None
    is_member: Optional[StrictBool] = None
    is_nonprofit: Optional[StrictBool] = None
    last_contact_date: Optional[StrictStr] = None
    last_purchase_date: Optional[StrictStr] = None
    leitweg_id: Optional[StrictStr] = None
    lifetime_value: Optional[StrictStr] = None
    mandate_date: Optional[StrictStr] = None
    mandate_reference: Optional[StrictStr] = None
    marketing_consent: Optional[StrictBool] = None
    marketing_consent_at: Optional[StrictStr] = None
    marketing_consent_source: Optional[StrictStr] = None
    mobile: Optional[StrictStr] = None
    name: StrictStr
    next_contact_date: Optional[StrictStr] = None
    notes: Optional[StrictStr] = None
    opening_balance: Optional[StrictStr] = None
    opening_balance_date: Optional[StrictStr] = None
    order_reference: Optional[StrictStr] = None
    payment_block: Optional[StrictBool] = None
    payment_grace_period_days: Optional[StrictInt] = None
    payment_methods: Optional[List[StrictStr]] = None
    payment_terms: Optional[StrictStr] = None
    phone: Optional[StrictStr] = None
    rating: Optional[StrictInt] = None
    sales_representative: Optional[StrictStr] = None
    social_media: Optional[Any]
    source: Optional[StrictStr] = None
    state: Optional[StrictStr] = None
    street: Optional[StrictStr] = None
    street_number: Optional[StrictStr] = None
    supplier_number: Optional[StrictStr] = None
    tags: Optional[List[StrictStr]] = None
    tax_country: Optional[StrictStr] = None
    tax_number: Optional[StrictStr] = None
    tax_office: Optional[StrictStr] = None
    total_invoices: Optional[StrictInt] = None
    total_revenue: Optional[StrictStr] = None
    updated_at: Optional[StrictStr] = None
    vat_id: Optional[StrictStr] = None
    vat_id_validated: Optional[StrictBool] = None
    vat_id_validation_date: Optional[StrictStr] = None
    website: Optional[StrictStr] = None
    zip: Optional[StrictStr] = None
    __properties: ClassVar[List[str]] = ["account_holder", "acquisition_cost", "address_supplement", "attention", "bank_name", "bic", "buyer_reference", "category", "certificate_authority", "certificate_number", "certificate_paragraph", "certificate_valid_until", "city", "company_name", "contact_id", "contact_persons", "contact_type", "country", "created_at", "credit_limit", "creditor_account_skr03", "creditor_account_skr04", "currency", "customer_number", "debitor_account_skr03", "debitor_account_skr04", "default_debitor_number", "delivery_block", "department", "discount_days", "discount_percentage", "donation_receipt_eligible", "email", "external_id", "fax", "iban", "industry", "is_active", "is_member", "is_nonprofit", "last_contact_date", "last_purchase_date", "leitweg_id", "lifetime_value", "mandate_date", "mandate_reference", "marketing_consent", "marketing_consent_at", "marketing_consent_source", "mobile", "name", "next_contact_date", "notes", "opening_balance", "opening_balance_date", "order_reference", "payment_block", "payment_grace_period_days", "payment_methods", "payment_terms", "phone", "rating", "sales_representative", "social_media", "source", "state", "street", "street_number", "supplier_number", "tags", "tax_country", "tax_number", "tax_office", "total_invoices", "total_revenue", "updated_at", "vat_id", "vat_id_validated", "vat_id_validation_date", "website", "zip"]

    model_config = ConfigDict(
        validate_by_name=True,
        validate_by_alias=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        return json.dumps(to_jsonable_python(self.to_dict()))

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of Contact from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        * OpenAPI `readOnly` fields are excluded.
        * OpenAPI `readOnly` fields are excluded.
        """
        excluded_fields: Set[str] = set([
            "created_at",
            "updated_at",
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # set to None if account_holder (nullable) is None
        # and model_fields_set contains the field
        if self.account_holder is None and "account_holder" in self.model_fields_set:
            _dict['account_holder'] = None

        # set to None if acquisition_cost (nullable) is None
        # and model_fields_set contains the field
        if self.acquisition_cost is None and "acquisition_cost" in self.model_fields_set:
            _dict['acquisition_cost'] = None

        # set to None if address_supplement (nullable) is None
        # and model_fields_set contains the field
        if self.address_supplement is None and "address_supplement" in self.model_fields_set:
            _dict['address_supplement'] = None

        # set to None if attention (nullable) is None
        # and model_fields_set contains the field
        if self.attention is None and "attention" in self.model_fields_set:
            _dict['attention'] = None

        # set to None if bank_name (nullable) is None
        # and model_fields_set contains the field
        if self.bank_name is None and "bank_name" in self.model_fields_set:
            _dict['bank_name'] = None

        # set to None if bic (nullable) is None
        # and model_fields_set contains the field
        if self.bic is None and "bic" in self.model_fields_set:
            _dict['bic'] = None

        # set to None if buyer_reference (nullable) is None
        # and model_fields_set contains the field
        if self.buyer_reference is None and "buyer_reference" in self.model_fields_set:
            _dict['buyer_reference'] = None

        # set to None if category (nullable) is None
        # and model_fields_set contains the field
        if self.category is None and "category" in self.model_fields_set:
            _dict['category'] = None

        # set to None if certificate_authority (nullable) is None
        # and model_fields_set contains the field
        if self.certificate_authority is None and "certificate_authority" in self.model_fields_set:
            _dict['certificate_authority'] = None

        # set to None if certificate_number (nullable) is None
        # and model_fields_set contains the field
        if self.certificate_number is None and "certificate_number" in self.model_fields_set:
            _dict['certificate_number'] = None

        # set to None if certificate_paragraph (nullable) is None
        # and model_fields_set contains the field
        if self.certificate_paragraph is None and "certificate_paragraph" in self.model_fields_set:
            _dict['certificate_paragraph'] = None

        # set to None if certificate_valid_until (nullable) is None
        # and model_fields_set contains the field
        if self.certificate_valid_until is None and "certificate_valid_until" in self.model_fields_set:
            _dict['certificate_valid_until'] = None

        # set to None if city (nullable) is None
        # and model_fields_set contains the field
        if self.city is None and "city" in self.model_fields_set:
            _dict['city'] = None

        # set to None if company_name (nullable) is None
        # and model_fields_set contains the field
        if self.company_name is None and "company_name" in self.model_fields_set:
            _dict['company_name'] = None

        # set to None if contact_persons (nullable) is None
        # and model_fields_set contains the field
        if self.contact_persons is None and "contact_persons" in self.model_fields_set:
            _dict['contact_persons'] = None

        # set to None if country (nullable) is None
        # and model_fields_set contains the field
        if self.country is None and "country" in self.model_fields_set:
            _dict['country'] = None

        # set to None if credit_limit (nullable) is None
        # and model_fields_set contains the field
        if self.credit_limit is None and "credit_limit" in self.model_fields_set:
            _dict['credit_limit'] = None

        # set to None if creditor_account_skr03 (nullable) is None
        # and model_fields_set contains the field
        if self.creditor_account_skr03 is None and "creditor_account_skr03" in self.model_fields_set:
            _dict['creditor_account_skr03'] = None

        # set to None if creditor_account_skr04 (nullable) is None
        # and model_fields_set contains the field
        if self.creditor_account_skr04 is None and "creditor_account_skr04" in self.model_fields_set:
            _dict['creditor_account_skr04'] = None

        # set to None if currency (nullable) is None
        # and model_fields_set contains the field
        if self.currency is None and "currency" in self.model_fields_set:
            _dict['currency'] = None

        # set to None if customer_number (nullable) is None
        # and model_fields_set contains the field
        if self.customer_number is None and "customer_number" in self.model_fields_set:
            _dict['customer_number'] = None

        # set to None if debitor_account_skr03 (nullable) is None
        # and model_fields_set contains the field
        if self.debitor_account_skr03 is None and "debitor_account_skr03" in self.model_fields_set:
            _dict['debitor_account_skr03'] = None

        # set to None if debitor_account_skr04 (nullable) is None
        # and model_fields_set contains the field
        if self.debitor_account_skr04 is None and "debitor_account_skr04" in self.model_fields_set:
            _dict['debitor_account_skr04'] = None

        # set to None if default_debitor_number (nullable) is None
        # and model_fields_set contains the field
        if self.default_debitor_number is None and "default_debitor_number" in self.model_fields_set:
            _dict['default_debitor_number'] = None

        # set to None if delivery_block (nullable) is None
        # and model_fields_set contains the field
        if self.delivery_block is None and "delivery_block" in self.model_fields_set:
            _dict['delivery_block'] = None

        # set to None if department (nullable) is None
        # and model_fields_set contains the field
        if self.department is None and "department" in self.model_fields_set:
            _dict['department'] = None

        # set to None if discount_days (nullable) is None
        # and model_fields_set contains the field
        if self.discount_days is None and "discount_days" in self.model_fields_set:
            _dict['discount_days'] = None

        # set to None if discount_percentage (nullable) is None
        # and model_fields_set contains the field
        if self.discount_percentage is None and "discount_percentage" in self.model_fields_set:
            _dict['discount_percentage'] = None

        # set to None if donation_receipt_eligible (nullable) is None
        # and model_fields_set contains the field
        if self.donation_receipt_eligible is None and "donation_receipt_eligible" in self.model_fields_set:
            _dict['donation_receipt_eligible'] = None

        # set to None if email (nullable) is None
        # and model_fields_set contains the field
        if self.email is None and "email" in self.model_fields_set:
            _dict['email'] = None

        # set to None if external_id (nullable) is None
        # and model_fields_set contains the field
        if self.external_id is None and "external_id" in self.model_fields_set:
            _dict['external_id'] = None

        # set to None if fax (nullable) is None
        # and model_fields_set contains the field
        if self.fax is None and "fax" in self.model_fields_set:
            _dict['fax'] = None

        # set to None if iban (nullable) is None
        # and model_fields_set contains the field
        if self.iban is None and "iban" in self.model_fields_set:
            _dict['iban'] = None

        # set to None if industry (nullable) is None
        # and model_fields_set contains the field
        if self.industry is None and "industry" in self.model_fields_set:
            _dict['industry'] = None

        # set to None if is_active (nullable) is None
        # and model_fields_set contains the field
        if self.is_active is None and "is_active" in self.model_fields_set:
            _dict['is_active'] = None

        # set to None if is_member (nullable) is None
        # and model_fields_set contains the field
        if self.is_member is None and "is_member" in self.model_fields_set:
            _dict['is_member'] = None

        # set to None if is_nonprofit (nullable) is None
        # and model_fields_set contains the field
        if self.is_nonprofit is None and "is_nonprofit" in self.model_fields_set:
            _dict['is_nonprofit'] = None

        # set to None if last_contact_date (nullable) is None
        # and model_fields_set contains the field
        if self.last_contact_date is None and "last_contact_date" in self.model_fields_set:
            _dict['last_contact_date'] = None

        # set to None if last_purchase_date (nullable) is None
        # and model_fields_set contains the field
        if self.last_purchase_date is None and "last_purchase_date" in self.model_fields_set:
            _dict['last_purchase_date'] = None

        # set to None if leitweg_id (nullable) is None
        # and model_fields_set contains the field
        if self.leitweg_id is None and "leitweg_id" in self.model_fields_set:
            _dict['leitweg_id'] = None

        # set to None if lifetime_value (nullable) is None
        # and model_fields_set contains the field
        if self.lifetime_value is None and "lifetime_value" in self.model_fields_set:
            _dict['lifetime_value'] = None

        # set to None if mandate_date (nullable) is None
        # and model_fields_set contains the field
        if self.mandate_date is None and "mandate_date" in self.model_fields_set:
            _dict['mandate_date'] = None

        # set to None if mandate_reference (nullable) is None
        # and model_fields_set contains the field
        if self.mandate_reference is None and "mandate_reference" in self.model_fields_set:
            _dict['mandate_reference'] = None

        # set to None if marketing_consent (nullable) is None
        # and model_fields_set contains the field
        if self.marketing_consent is None and "marketing_consent" in self.model_fields_set:
            _dict['marketing_consent'] = None

        # set to None if marketing_consent_at (nullable) is None
        # and model_fields_set contains the field
        if self.marketing_consent_at is None and "marketing_consent_at" in self.model_fields_set:
            _dict['marketing_consent_at'] = None

        # set to None if marketing_consent_source (nullable) is None
        # and model_fields_set contains the field
        if self.marketing_consent_source is None and "marketing_consent_source" in self.model_fields_set:
            _dict['marketing_consent_source'] = None

        # set to None if mobile (nullable) is None
        # and model_fields_set contains the field
        if self.mobile is None and "mobile" in self.model_fields_set:
            _dict['mobile'] = None

        # set to None if next_contact_date (nullable) is None
        # and model_fields_set contains the field
        if self.next_contact_date is None and "next_contact_date" in self.model_fields_set:
            _dict['next_contact_date'] = None

        # set to None if notes (nullable) is None
        # and model_fields_set contains the field
        if self.notes is None and "notes" in self.model_fields_set:
            _dict['notes'] = None

        # set to None if opening_balance (nullable) is None
        # and model_fields_set contains the field
        if self.opening_balance is None and "opening_balance" in self.model_fields_set:
            _dict['opening_balance'] = None

        # set to None if opening_balance_date (nullable) is None
        # and model_fields_set contains the field
        if self.opening_balance_date is None and "opening_balance_date" in self.model_fields_set:
            _dict['opening_balance_date'] = None

        # set to None if order_reference (nullable) is None
        # and model_fields_set contains the field
        if self.order_reference is None and "order_reference" in self.model_fields_set:
            _dict['order_reference'] = None

        # set to None if payment_block (nullable) is None
        # and model_fields_set contains the field
        if self.payment_block is None and "payment_block" in self.model_fields_set:
            _dict['payment_block'] = None

        # set to None if payment_grace_period_days (nullable) is None
        # and model_fields_set contains the field
        if self.payment_grace_period_days is None and "payment_grace_period_days" in self.model_fields_set:
            _dict['payment_grace_period_days'] = None

        # set to None if payment_methods (nullable) is None
        # and model_fields_set contains the field
        if self.payment_methods is None and "payment_methods" in self.model_fields_set:
            _dict['payment_methods'] = None

        # set to None if payment_terms (nullable) is None
        # and model_fields_set contains the field
        if self.payment_terms is None and "payment_terms" in self.model_fields_set:
            _dict['payment_terms'] = None

        # set to None if phone (nullable) is None
        # and model_fields_set contains the field
        if self.phone is None and "phone" in self.model_fields_set:
            _dict['phone'] = None

        # set to None if rating (nullable) is None
        # and model_fields_set contains the field
        if self.rating is None and "rating" in self.model_fields_set:
            _dict['rating'] = None

        # set to None if sales_representative (nullable) is None
        # and model_fields_set contains the field
        if self.sales_representative is None and "sales_representative" in self.model_fields_set:
            _dict['sales_representative'] = None

        # set to None if social_media (nullable) is None
        # and model_fields_set contains the field
        if self.social_media is None and "social_media" in self.model_fields_set:
            _dict['social_media'] = None

        # set to None if source (nullable) is None
        # and model_fields_set contains the field
        if self.source is None and "source" in self.model_fields_set:
            _dict['source'] = None

        # set to None if state (nullable) is None
        # and model_fields_set contains the field
        if self.state is None and "state" in self.model_fields_set:
            _dict['state'] = None

        # set to None if street (nullable) is None
        # and model_fields_set contains the field
        if self.street is None and "street" in self.model_fields_set:
            _dict['street'] = None

        # set to None if street_number (nullable) is None
        # and model_fields_set contains the field
        if self.street_number is None and "street_number" in self.model_fields_set:
            _dict['street_number'] = None

        # set to None if supplier_number (nullable) is None
        # and model_fields_set contains the field
        if self.supplier_number is None and "supplier_number" in self.model_fields_set:
            _dict['supplier_number'] = None

        # set to None if tags (nullable) is None
        # and model_fields_set contains the field
        if self.tags is None and "tags" in self.model_fields_set:
            _dict['tags'] = None

        # set to None if tax_country (nullable) is None
        # and model_fields_set contains the field
        if self.tax_country is None and "tax_country" in self.model_fields_set:
            _dict['tax_country'] = None

        # set to None if tax_number (nullable) is None
        # and model_fields_set contains the field
        if self.tax_number is None and "tax_number" in self.model_fields_set:
            _dict['tax_number'] = None

        # set to None if tax_office (nullable) is None
        # and model_fields_set contains the field
        if self.tax_office is None and "tax_office" in self.model_fields_set:
            _dict['tax_office'] = None

        # set to None if total_invoices (nullable) is None
        # and model_fields_set contains the field
        if self.total_invoices is None and "total_invoices" in self.model_fields_set:
            _dict['total_invoices'] = None

        # set to None if total_revenue (nullable) is None
        # and model_fields_set contains the field
        if self.total_revenue is None and "total_revenue" in self.model_fields_set:
            _dict['total_revenue'] = None

        # set to None if updated_at (nullable) is None
        # and model_fields_set contains the field
        if self.updated_at is None and "updated_at" in self.model_fields_set:
            _dict['updated_at'] = None

        # set to None if vat_id (nullable) is None
        # and model_fields_set contains the field
        if self.vat_id is None and "vat_id" in self.model_fields_set:
            _dict['vat_id'] = None

        # set to None if vat_id_validated (nullable) is None
        # and model_fields_set contains the field
        if self.vat_id_validated is None and "vat_id_validated" in self.model_fields_set:
            _dict['vat_id_validated'] = None

        # set to None if vat_id_validation_date (nullable) is None
        # and model_fields_set contains the field
        if self.vat_id_validation_date is None and "vat_id_validation_date" in self.model_fields_set:
            _dict['vat_id_validation_date'] = None

        # set to None if website (nullable) is None
        # and model_fields_set contains the field
        if self.website is None and "website" in self.model_fields_set:
            _dict['website'] = None

        # set to None if zip (nullable) is None
        # and model_fields_set contains the field
        if self.zip is None and "zip" in self.model_fields_set:
            _dict['zip'] = None

        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of Contact from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "account_holder": obj.get("account_holder"),
            "acquisition_cost": obj.get("acquisition_cost"),
            "address_supplement": obj.get("address_supplement"),
            "attention": obj.get("attention"),
            "bank_name": obj.get("bank_name"),
            "bic": obj.get("bic"),
            "buyer_reference": obj.get("buyer_reference"),
            "category": obj.get("category"),
            "certificate_authority": obj.get("certificate_authority"),
            "certificate_number": obj.get("certificate_number"),
            "certificate_paragraph": obj.get("certificate_paragraph"),
            "certificate_valid_until": obj.get("certificate_valid_until"),
            "city": obj.get("city"),
            "company_name": obj.get("company_name"),
            "contact_id": obj.get("contact_id"),
            "contact_persons": obj.get("contact_persons"),
            "contact_type": obj.get("contact_type"),
            "country": obj.get("country"),
            "created_at": obj.get("created_at"),
            "credit_limit": obj.get("credit_limit"),
            "creditor_account_skr03": obj.get("creditor_account_skr03"),
            "creditor_account_skr04": obj.get("creditor_account_skr04"),
            "currency": obj.get("currency"),
            "customer_number": obj.get("customer_number"),
            "debitor_account_skr03": obj.get("debitor_account_skr03"),
            "debitor_account_skr04": obj.get("debitor_account_skr04"),
            "default_debitor_number": obj.get("default_debitor_number"),
            "delivery_block": obj.get("delivery_block"),
            "department": obj.get("department"),
            "discount_days": obj.get("discount_days"),
            "discount_percentage": obj.get("discount_percentage"),
            "donation_receipt_eligible": obj.get("donation_receipt_eligible"),
            "email": obj.get("email"),
            "external_id": obj.get("external_id"),
            "fax": obj.get("fax"),
            "iban": obj.get("iban"),
            "industry": obj.get("industry"),
            "is_active": obj.get("is_active"),
            "is_member": obj.get("is_member"),
            "is_nonprofit": obj.get("is_nonprofit"),
            "last_contact_date": obj.get("last_contact_date"),
            "last_purchase_date": obj.get("last_purchase_date"),
            "leitweg_id": obj.get("leitweg_id"),
            "lifetime_value": obj.get("lifetime_value"),
            "mandate_date": obj.get("mandate_date"),
            "mandate_reference": obj.get("mandate_reference"),
            "marketing_consent": obj.get("marketing_consent"),
            "marketing_consent_at": obj.get("marketing_consent_at"),
            "marketing_consent_source": obj.get("marketing_consent_source"),
            "mobile": obj.get("mobile"),
            "name": obj.get("name"),
            "next_contact_date": obj.get("next_contact_date"),
            "notes": obj.get("notes"),
            "opening_balance": obj.get("opening_balance"),
            "opening_balance_date": obj.get("opening_balance_date"),
            "order_reference": obj.get("order_reference"),
            "payment_block": obj.get("payment_block"),
            "payment_grace_period_days": obj.get("payment_grace_period_days"),
            "payment_methods": obj.get("payment_methods"),
            "payment_terms": obj.get("payment_terms"),
            "phone": obj.get("phone"),
            "rating": obj.get("rating"),
            "sales_representative": obj.get("sales_representative"),
            "social_media": obj.get("social_media"),
            "source": obj.get("source"),
            "state": obj.get("state"),
            "street": obj.get("street"),
            "street_number": obj.get("street_number"),
            "supplier_number": obj.get("supplier_number"),
            "tags": obj.get("tags"),
            "tax_country": obj.get("tax_country"),
            "tax_number": obj.get("tax_number"),
            "tax_office": obj.get("tax_office"),
            "total_invoices": obj.get("total_invoices"),
            "total_revenue": obj.get("total_revenue"),
            "updated_at": obj.get("updated_at"),
            "vat_id": obj.get("vat_id"),
            "vat_id_validated": obj.get("vat_id_validated"),
            "vat_id_validation_date": obj.get("vat_id_validation_date"),
            "website": obj.get("website"),
            "zip": obj.get("zip")
        })
        return _obj


