# coding: utf-8

"""
    SimpleBilly API

    Simplebilly API - Bookkeeping, CRM, ERP. Multi-tenant API: a tenant is isolated and routed by subdomain (or a configured custom domain) under the base domain.  ## Rate limiting All endpoints are rate-limited per client IP: **100 requests per minute** on API routes and **5 requests per minute** on authentication routes. Exceeding a limit returns `429 Too Many Requests`; the window resets after 60 seconds.

    The version of the OpenAPI document: 0.1.0
    Contact: support@simplebilly.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from datetime import date, datetime
from pydantic import BaseModel, ConfigDict, Field, StrictBool, StrictInt, StrictStr, field_validator
from typing import Any, ClassVar, Dict, List, Optional
from typing_extensions import Annotated
from simplebilly_api.models.contact_type import ContactType
from simplebilly_api.models.country_code import CountryCode
from simplebilly_api.models.sepa_sequence_type import SepaSequenceType
from typing import Optional, Set
from typing_extensions import Self
from pydantic_core import to_jsonable_python

class ContactUpdate(BaseModel):
    """
    ContactUpdate
    """ # noqa: E501
    account_holder: Optional[Annotated[str, Field(strict=True, max_length=100)]] = Field(default=None, alias="accountHolder")
    acquisition_cost: Optional[StrictStr] = Field(default=None, alias="acquisitionCost")
    address_supplement: Optional[Annotated[str, Field(strict=True, max_length=100)]] = Field(default=None, alias="addressSupplement")
    attention: Optional[Annotated[str, Field(strict=True, max_length=255)]] = None
    bank_name: Optional[Annotated[str, Field(strict=True, max_length=100)]] = Field(default=None, alias="bankName")
    bic: Optional[Annotated[str, Field(strict=True)]] = None
    buyer_reference: Optional[Annotated[str, Field(strict=True, max_length=50)]] = Field(default=None, alias="buyerReference")
    category: Optional[Annotated[str, Field(strict=True, max_length=100)]] = None
    certificate_authority: Optional[Annotated[str, Field(strict=True, max_length=100)]] = Field(default=None, alias="certificateAuthority")
    certificate_number: Optional[Annotated[str, Field(strict=True, max_length=50)]] = Field(default=None, alias="certificateNumber")
    certificate_paragraph: Optional[Annotated[str, Field(strict=True, max_length=50)]] = Field(default=None, alias="certificateParagraph")
    certificate_valid_until: Optional[date] = Field(default=None, alias="certificateValidUntil")
    city: Optional[Annotated[str, Field(strict=True, max_length=100)]] = None
    company_name: Optional[Annotated[str, Field(strict=True, max_length=255)]] = Field(default=None, alias="companyName")
    contact_persons: Optional[Any] = Field(default=None, alias="contactPersons")
    contact_type: Optional[ContactType] = Field(default=None, alias="contactType")
    country: Optional[CountryCode] = None
    credit_limit: Optional[StrictStr] = Field(default=None, alias="creditLimit")
    creditor_account_skr03: Optional[Annotated[str, Field(strict=True, max_length=10)]] = Field(default=None, alias="creditorAccountSkr03")
    creditor_account_skr04: Optional[Annotated[str, Field(strict=True, max_length=10)]] = Field(default=None, alias="creditorAccountSkr04")
    currency: Optional[Annotated[str, Field(strict=True, max_length=3)]] = None
    custom_fields: Optional[Any] = Field(default=None, alias="customFields")
    customer_number: Optional[Annotated[str, Field(strict=True, max_length=50)]] = Field(default=None, alias="customerNumber")
    debitor_account_skr03: Optional[Annotated[str, Field(strict=True, max_length=10)]] = Field(default=None, alias="debitorAccountSkr03")
    debitor_account_skr04: Optional[Annotated[str, Field(strict=True, max_length=10)]] = Field(default=None, alias="debitorAccountSkr04")
    default_debitor_number: Optional[Annotated[str, Field(strict=True, max_length=50)]] = Field(default=None, alias="defaultDebitorNumber")
    delivery_block: Optional[StrictBool] = Field(default=None, alias="deliveryBlock")
    department: Optional[Annotated[str, Field(strict=True, max_length=100)]] = None
    discount_days: Optional[Annotated[int, Field(le=365, strict=True, ge=0)]] = Field(default=None, alias="discountDays")
    discount_percentage: Optional[StrictStr] = Field(default=None, alias="discountPercentage")
    donation_receipt_eligible: Optional[StrictBool] = Field(default=None, alias="donationReceiptEligible")
    email: Optional[StrictStr] = None
    external_id: Optional[Annotated[str, Field(strict=True, max_length=100)]] = Field(default=None, alias="externalId")
    fax: Optional[Annotated[str, Field(strict=True)]] = None
    iban: Optional[Annotated[str, Field(strict=True)]] = None
    industry: Optional[Annotated[str, Field(strict=True, max_length=100)]] = None
    is_active: Optional[StrictBool] = Field(default=None, alias="isActive")
    is_member: Optional[StrictBool] = Field(default=None, alias="isMember")
    is_nonprofit: Optional[StrictBool] = Field(default=None, alias="isNonprofit")
    last_contact_date: Optional[date] = Field(default=None, alias="lastContactDate")
    last_purchase_date: Optional[date] = Field(default=None, alias="lastPurchaseDate")
    leitweg_id: Optional[Annotated[str, Field(strict=True, max_length=50)]] = Field(default=None, alias="leitwegId")
    lifetime_value: Optional[StrictStr] = Field(default=None, alias="lifetimeValue")
    mandate_date: Optional[date] = Field(default=None, alias="mandateDate")
    mandate_reference: Optional[Annotated[str, Field(strict=True, max_length=35)]] = Field(default=None, alias="mandateReference")
    marketing_consent: Optional[StrictBool] = Field(default=None, alias="marketingConsent")
    marketing_consent_at: Optional[datetime] = Field(default=None, alias="marketingConsentAt")
    marketing_consent_source: Optional[StrictStr] = Field(default=None, alias="marketingConsentSource")
    mobile: Optional[Annotated[str, Field(strict=True)]] = None
    name: Optional[Annotated[str, Field(min_length=1, strict=True, max_length=255)]] = None
    next_contact_date: Optional[date] = Field(default=None, alias="nextContactDate")
    notes: Optional[Annotated[str, Field(strict=True, max_length=10000)]] = None
    opening_balance: Optional[StrictStr] = Field(default=None, alias="openingBalance")
    opening_balance_date: Optional[date] = Field(default=None, alias="openingBalanceDate")
    order_reference: Optional[Annotated[str, Field(strict=True, max_length=50)]] = Field(default=None, alias="orderReference")
    payment_block: Optional[StrictBool] = Field(default=None, alias="paymentBlock")
    payment_grace_period_days: Optional[Annotated[int, Field(le=365, strict=True, ge=0)]] = Field(default=None, alias="paymentGracePeriodDays")
    payment_methods: Optional[List[StrictStr]] = Field(default=None, alias="paymentMethods")
    payment_terms: Optional[Annotated[str, Field(strict=True, max_length=100)]] = Field(default=None, alias="paymentTerms")
    phone: Optional[Annotated[str, Field(strict=True)]] = None
    rating: Optional[Annotated[int, Field(le=5, strict=True, ge=1)]] = None
    sales_representative: Optional[Annotated[str, Field(strict=True, max_length=100)]] = Field(default=None, alias="salesRepresentative")
    sepa_batch_booking: Optional[StrictBool] = Field(default=None, alias="sepaBatchBooking")
    sepa_sequence_type: Optional[SepaSequenceType] = Field(default=None, alias="sepaSequenceType")
    social_media: Optional[Any] = Field(default=None, alias="socialMedia")
    source: Optional[Annotated[str, Field(strict=True, max_length=100)]] = None
    state: Optional[Annotated[str, Field(strict=True, max_length=100)]] = None
    street: Optional[Annotated[str, Field(strict=True, max_length=255)]] = None
    street_number: Optional[Annotated[str, Field(strict=True, max_length=50)]] = Field(default=None, alias="streetNumber")
    supplier_number: Optional[Annotated[str, Field(strict=True, max_length=50)]] = Field(default=None, alias="supplierNumber")
    tags: Optional[List[StrictStr]] = None
    tax_country: Optional[CountryCode] = Field(default=None, alias="taxCountry")
    tax_number: Optional[Annotated[str, Field(strict=True, max_length=30)]] = Field(default=None, alias="taxNumber")
    tax_office: Optional[Annotated[str, Field(strict=True, max_length=100)]] = Field(default=None, alias="taxOffice")
    total_invoices: Optional[StrictInt] = Field(default=None, alias="totalInvoices")
    total_revenue: Optional[StrictStr] = Field(default=None, alias="totalRevenue")
    vat_id: Optional[Annotated[str, Field(strict=True)]] = Field(default=None, alias="vatId")
    vat_id_validated: Optional[StrictBool] = Field(default=None, alias="vatIdValidated")
    vat_id_validation_date: Optional[date] = Field(default=None, alias="vatIdValidationDate")
    website: Optional[Annotated[str, Field(strict=True, max_length=2048)]] = None
    zip: Optional[Annotated[str, Field(strict=True, max_length=20)]] = None
    __properties: ClassVar[List[str]] = ["accountHolder", "acquisitionCost", "addressSupplement", "attention", "bankName", "bic", "buyerReference", "category", "certificateAuthority", "certificateNumber", "certificateParagraph", "certificateValidUntil", "city", "companyName", "contactPersons", "contactType", "country", "creditLimit", "creditorAccountSkr03", "creditorAccountSkr04", "currency", "customFields", "customerNumber", "debitorAccountSkr03", "debitorAccountSkr04", "defaultDebitorNumber", "deliveryBlock", "department", "discountDays", "discountPercentage", "donationReceiptEligible", "email", "externalId", "fax", "iban", "industry", "isActive", "isMember", "isNonprofit", "lastContactDate", "lastPurchaseDate", "leitwegId", "lifetimeValue", "mandateDate", "mandateReference", "marketingConsent", "marketingConsentAt", "marketingConsentSource", "mobile", "name", "nextContactDate", "notes", "openingBalance", "openingBalanceDate", "orderReference", "paymentBlock", "paymentGracePeriodDays", "paymentMethods", "paymentTerms", "phone", "rating", "salesRepresentative", "sepaBatchBooking", "sepaSequenceType", "socialMedia", "source", "state", "street", "streetNumber", "supplierNumber", "tags", "taxCountry", "taxNumber", "taxOffice", "totalInvoices", "totalRevenue", "vatId", "vatIdValidated", "vatIdValidationDate", "website", "zip"]

    @field_validator('bic', mode="before")
    def bic_validate_regular_expression(cls, value):
        """Validates the regular expression"""
        if value is None:
            return value

        if isinstance(value, str) and not re.match(r"^[A-Z]{6}[A-Z0-9]{2}([A-Z0-9]{3})?$", value):
            raise ValueError(r"must validate the regular expression /^[A-Z]{6}[A-Z0-9]{2}([A-Z0-9]{3})?$/")
        return value

    @field_validator('fax', mode="before")
    def fax_validate_regular_expression(cls, value):
        """Validates the regular expression"""
        if value is None:
            return value

        if isinstance(value, str) and not re.match(r"^\+?[0-9\s\-\(\)]{7,20}$", value):
            raise ValueError(r"must validate the regular expression /^\+?[0-9\s\-\(\)]{7,20}$/")
        return value

    @field_validator('iban', mode="before")
    def iban_validate_regular_expression(cls, value):
        """Validates the regular expression"""
        if value is None:
            return value

        if isinstance(value, str) and not re.match(r"^[A-Z]{2}\d{2}[A-Z0-9]{4,30}$", value):
            raise ValueError(r"must validate the regular expression /^[A-Z]{2}\d{2}[A-Z0-9]{4,30}$/")
        return value

    @field_validator('mobile', mode="before")
    def mobile_validate_regular_expression(cls, value):
        """Validates the regular expression"""
        if value is None:
            return value

        if isinstance(value, str) and not re.match(r"^\+?[0-9\s\-\(\)]{7,20}$", value):
            raise ValueError(r"must validate the regular expression /^\+?[0-9\s\-\(\)]{7,20}$/")
        return value

    @field_validator('phone', mode="before")
    def phone_validate_regular_expression(cls, value):
        """Validates the regular expression"""
        if value is None:
            return value

        if isinstance(value, str) and not re.match(r"^\+?[0-9\s\-\(\)]{7,20}$", value):
            raise ValueError(r"must validate the regular expression /^\+?[0-9\s\-\(\)]{7,20}$/")
        return value

    @field_validator('vat_id', mode="before")
    def vat_id_validate_regular_expression(cls, value):
        """Validates the regular expression"""
        if value is None:
            return value

        if isinstance(value, str) and not re.match(r"^[A-Z]{2}[0-9A-Z]{8,15}$", value):
            raise ValueError(r"must validate the regular expression /^[A-Z]{2}[0-9A-Z]{8,15}$/")
        return value

    model_config = ConfigDict(
        validate_by_name=True,
        validate_by_alias=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        return json.dumps(to_jsonable_python(self.to_dict()))

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of ContactUpdate from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # set to None if account_holder (nullable) is None
        # and model_fields_set contains the field
        if self.account_holder is None and "account_holder" in self.model_fields_set:
            _dict['accountHolder'] = None

        # set to None if acquisition_cost (nullable) is None
        # and model_fields_set contains the field
        if self.acquisition_cost is None and "acquisition_cost" in self.model_fields_set:
            _dict['acquisitionCost'] = None

        # set to None if address_supplement (nullable) is None
        # and model_fields_set contains the field
        if self.address_supplement is None and "address_supplement" in self.model_fields_set:
            _dict['addressSupplement'] = None

        # set to None if attention (nullable) is None
        # and model_fields_set contains the field
        if self.attention is None and "attention" in self.model_fields_set:
            _dict['attention'] = None

        # set to None if bank_name (nullable) is None
        # and model_fields_set contains the field
        if self.bank_name is None and "bank_name" in self.model_fields_set:
            _dict['bankName'] = None

        # set to None if bic (nullable) is None
        # and model_fields_set contains the field
        if self.bic is None and "bic" in self.model_fields_set:
            _dict['bic'] = None

        # set to None if buyer_reference (nullable) is None
        # and model_fields_set contains the field
        if self.buyer_reference is None and "buyer_reference" in self.model_fields_set:
            _dict['buyerReference'] = None

        # set to None if category (nullable) is None
        # and model_fields_set contains the field
        if self.category is None and "category" in self.model_fields_set:
            _dict['category'] = None

        # set to None if certificate_authority (nullable) is None
        # and model_fields_set contains the field
        if self.certificate_authority is None and "certificate_authority" in self.model_fields_set:
            _dict['certificateAuthority'] = None

        # set to None if certificate_number (nullable) is None
        # and model_fields_set contains the field
        if self.certificate_number is None and "certificate_number" in self.model_fields_set:
            _dict['certificateNumber'] = None

        # set to None if certificate_paragraph (nullable) is None
        # and model_fields_set contains the field
        if self.certificate_paragraph is None and "certificate_paragraph" in self.model_fields_set:
            _dict['certificateParagraph'] = None

        # set to None if certificate_valid_until (nullable) is None
        # and model_fields_set contains the field
        if self.certificate_valid_until is None and "certificate_valid_until" in self.model_fields_set:
            _dict['certificateValidUntil'] = None

        # set to None if city (nullable) is None
        # and model_fields_set contains the field
        if self.city is None and "city" in self.model_fields_set:
            _dict['city'] = None

        # set to None if company_name (nullable) is None
        # and model_fields_set contains the field
        if self.company_name is None and "company_name" in self.model_fields_set:
            _dict['companyName'] = None

        # set to None if contact_persons (nullable) is None
        # and model_fields_set contains the field
        if self.contact_persons is None and "contact_persons" in self.model_fields_set:
            _dict['contactPersons'] = None

        # set to None if contact_type (nullable) is None
        # and model_fields_set contains the field
        if self.contact_type is None and "contact_type" in self.model_fields_set:
            _dict['contactType'] = None

        # set to None if country (nullable) is None
        # and model_fields_set contains the field
        if self.country is None and "country" in self.model_fields_set:
            _dict['country'] = None

        # set to None if credit_limit (nullable) is None
        # and model_fields_set contains the field
        if self.credit_limit is None and "credit_limit" in self.model_fields_set:
            _dict['creditLimit'] = None

        # set to None if creditor_account_skr03 (nullable) is None
        # and model_fields_set contains the field
        if self.creditor_account_skr03 is None and "creditor_account_skr03" in self.model_fields_set:
            _dict['creditorAccountSkr03'] = None

        # set to None if creditor_account_skr04 (nullable) is None
        # and model_fields_set contains the field
        if self.creditor_account_skr04 is None and "creditor_account_skr04" in self.model_fields_set:
            _dict['creditorAccountSkr04'] = None

        # set to None if currency (nullable) is None
        # and model_fields_set contains the field
        if self.currency is None and "currency" in self.model_fields_set:
            _dict['currency'] = None

        # set to None if custom_fields (nullable) is None
        # and model_fields_set contains the field
        if self.custom_fields is None and "custom_fields" in self.model_fields_set:
            _dict['customFields'] = None

        # set to None if customer_number (nullable) is None
        # and model_fields_set contains the field
        if self.customer_number is None and "customer_number" in self.model_fields_set:
            _dict['customerNumber'] = None

        # set to None if debitor_account_skr03 (nullable) is None
        # and model_fields_set contains the field
        if self.debitor_account_skr03 is None and "debitor_account_skr03" in self.model_fields_set:
            _dict['debitorAccountSkr03'] = None

        # set to None if debitor_account_skr04 (nullable) is None
        # and model_fields_set contains the field
        if self.debitor_account_skr04 is None and "debitor_account_skr04" in self.model_fields_set:
            _dict['debitorAccountSkr04'] = None

        # set to None if default_debitor_number (nullable) is None
        # and model_fields_set contains the field
        if self.default_debitor_number is None and "default_debitor_number" in self.model_fields_set:
            _dict['defaultDebitorNumber'] = None

        # set to None if delivery_block (nullable) is None
        # and model_fields_set contains the field
        if self.delivery_block is None and "delivery_block" in self.model_fields_set:
            _dict['deliveryBlock'] = None

        # set to None if department (nullable) is None
        # and model_fields_set contains the field
        if self.department is None and "department" in self.model_fields_set:
            _dict['department'] = None

        # set to None if discount_days (nullable) is None
        # and model_fields_set contains the field
        if self.discount_days is None and "discount_days" in self.model_fields_set:
            _dict['discountDays'] = None

        # set to None if discount_percentage (nullable) is None
        # and model_fields_set contains the field
        if self.discount_percentage is None and "discount_percentage" in self.model_fields_set:
            _dict['discountPercentage'] = None

        # set to None if donation_receipt_eligible (nullable) is None
        # and model_fields_set contains the field
        if self.donation_receipt_eligible is None and "donation_receipt_eligible" in self.model_fields_set:
            _dict['donationReceiptEligible'] = None

        # set to None if email (nullable) is None
        # and model_fields_set contains the field
        if self.email is None and "email" in self.model_fields_set:
            _dict['email'] = None

        # set to None if external_id (nullable) is None
        # and model_fields_set contains the field
        if self.external_id is None and "external_id" in self.model_fields_set:
            _dict['externalId'] = None

        # set to None if fax (nullable) is None
        # and model_fields_set contains the field
        if self.fax is None and "fax" in self.model_fields_set:
            _dict['fax'] = None

        # set to None if iban (nullable) is None
        # and model_fields_set contains the field
        if self.iban is None and "iban" in self.model_fields_set:
            _dict['iban'] = None

        # set to None if industry (nullable) is None
        # and model_fields_set contains the field
        if self.industry is None and "industry" in self.model_fields_set:
            _dict['industry'] = None

        # set to None if is_active (nullable) is None
        # and model_fields_set contains the field
        if self.is_active is None and "is_active" in self.model_fields_set:
            _dict['isActive'] = None

        # set to None if is_member (nullable) is None
        # and model_fields_set contains the field
        if self.is_member is None and "is_member" in self.model_fields_set:
            _dict['isMember'] = None

        # set to None if is_nonprofit (nullable) is None
        # and model_fields_set contains the field
        if self.is_nonprofit is None and "is_nonprofit" in self.model_fields_set:
            _dict['isNonprofit'] = None

        # set to None if last_contact_date (nullable) is None
        # and model_fields_set contains the field
        if self.last_contact_date is None and "last_contact_date" in self.model_fields_set:
            _dict['lastContactDate'] = None

        # set to None if last_purchase_date (nullable) is None
        # and model_fields_set contains the field
        if self.last_purchase_date is None and "last_purchase_date" in self.model_fields_set:
            _dict['lastPurchaseDate'] = None

        # set to None if leitweg_id (nullable) is None
        # and model_fields_set contains the field
        if self.leitweg_id is None and "leitweg_id" in self.model_fields_set:
            _dict['leitwegId'] = None

        # set to None if lifetime_value (nullable) is None
        # and model_fields_set contains the field
        if self.lifetime_value is None and "lifetime_value" in self.model_fields_set:
            _dict['lifetimeValue'] = None

        # set to None if mandate_date (nullable) is None
        # and model_fields_set contains the field
        if self.mandate_date is None and "mandate_date" in self.model_fields_set:
            _dict['mandateDate'] = None

        # set to None if mandate_reference (nullable) is None
        # and model_fields_set contains the field
        if self.mandate_reference is None and "mandate_reference" in self.model_fields_set:
            _dict['mandateReference'] = None

        # set to None if marketing_consent (nullable) is None
        # and model_fields_set contains the field
        if self.marketing_consent is None and "marketing_consent" in self.model_fields_set:
            _dict['marketingConsent'] = None

        # set to None if marketing_consent_at (nullable) is None
        # and model_fields_set contains the field
        if self.marketing_consent_at is None and "marketing_consent_at" in self.model_fields_set:
            _dict['marketingConsentAt'] = None

        # set to None if marketing_consent_source (nullable) is None
        # and model_fields_set contains the field
        if self.marketing_consent_source is None and "marketing_consent_source" in self.model_fields_set:
            _dict['marketingConsentSource'] = None

        # set to None if mobile (nullable) is None
        # and model_fields_set contains the field
        if self.mobile is None and "mobile" in self.model_fields_set:
            _dict['mobile'] = None

        # set to None if name (nullable) is None
        # and model_fields_set contains the field
        if self.name is None and "name" in self.model_fields_set:
            _dict['name'] = None

        # set to None if next_contact_date (nullable) is None
        # and model_fields_set contains the field
        if self.next_contact_date is None and "next_contact_date" in self.model_fields_set:
            _dict['nextContactDate'] = None

        # set to None if notes (nullable) is None
        # and model_fields_set contains the field
        if self.notes is None and "notes" in self.model_fields_set:
            _dict['notes'] = None

        # set to None if opening_balance (nullable) is None
        # and model_fields_set contains the field
        if self.opening_balance is None and "opening_balance" in self.model_fields_set:
            _dict['openingBalance'] = None

        # set to None if opening_balance_date (nullable) is None
        # and model_fields_set contains the field
        if self.opening_balance_date is None and "opening_balance_date" in self.model_fields_set:
            _dict['openingBalanceDate'] = None

        # set to None if order_reference (nullable) is None
        # and model_fields_set contains the field
        if self.order_reference is None and "order_reference" in self.model_fields_set:
            _dict['orderReference'] = None

        # set to None if payment_block (nullable) is None
        # and model_fields_set contains the field
        if self.payment_block is None and "payment_block" in self.model_fields_set:
            _dict['paymentBlock'] = None

        # set to None if payment_grace_period_days (nullable) is None
        # and model_fields_set contains the field
        if self.payment_grace_period_days is None and "payment_grace_period_days" in self.model_fields_set:
            _dict['paymentGracePeriodDays'] = None

        # set to None if payment_methods (nullable) is None
        # and model_fields_set contains the field
        if self.payment_methods is None and "payment_methods" in self.model_fields_set:
            _dict['paymentMethods'] = None

        # set to None if payment_terms (nullable) is None
        # and model_fields_set contains the field
        if self.payment_terms is None and "payment_terms" in self.model_fields_set:
            _dict['paymentTerms'] = None

        # set to None if phone (nullable) is None
        # and model_fields_set contains the field
        if self.phone is None and "phone" in self.model_fields_set:
            _dict['phone'] = None

        # set to None if rating (nullable) is None
        # and model_fields_set contains the field
        if self.rating is None and "rating" in self.model_fields_set:
            _dict['rating'] = None

        # set to None if sales_representative (nullable) is None
        # and model_fields_set contains the field
        if self.sales_representative is None and "sales_representative" in self.model_fields_set:
            _dict['salesRepresentative'] = None

        # set to None if sepa_batch_booking (nullable) is None
        # and model_fields_set contains the field
        if self.sepa_batch_booking is None and "sepa_batch_booking" in self.model_fields_set:
            _dict['sepaBatchBooking'] = None

        # set to None if sepa_sequence_type (nullable) is None
        # and model_fields_set contains the field
        if self.sepa_sequence_type is None and "sepa_sequence_type" in self.model_fields_set:
            _dict['sepaSequenceType'] = None

        # set to None if social_media (nullable) is None
        # and model_fields_set contains the field
        if self.social_media is None and "social_media" in self.model_fields_set:
            _dict['socialMedia'] = None

        # set to None if source (nullable) is None
        # and model_fields_set contains the field
        if self.source is None and "source" in self.model_fields_set:
            _dict['source'] = None

        # set to None if state (nullable) is None
        # and model_fields_set contains the field
        if self.state is None and "state" in self.model_fields_set:
            _dict['state'] = None

        # set to None if street (nullable) is None
        # and model_fields_set contains the field
        if self.street is None and "street" in self.model_fields_set:
            _dict['street'] = None

        # set to None if street_number (nullable) is None
        # and model_fields_set contains the field
        if self.street_number is None and "street_number" in self.model_fields_set:
            _dict['streetNumber'] = None

        # set to None if supplier_number (nullable) is None
        # and model_fields_set contains the field
        if self.supplier_number is None and "supplier_number" in self.model_fields_set:
            _dict['supplierNumber'] = None

        # set to None if tags (nullable) is None
        # and model_fields_set contains the field
        if self.tags is None and "tags" in self.model_fields_set:
            _dict['tags'] = None

        # set to None if tax_country (nullable) is None
        # and model_fields_set contains the field
        if self.tax_country is None and "tax_country" in self.model_fields_set:
            _dict['taxCountry'] = None

        # set to None if tax_number (nullable) is None
        # and model_fields_set contains the field
        if self.tax_number is None and "tax_number" in self.model_fields_set:
            _dict['taxNumber'] = None

        # set to None if tax_office (nullable) is None
        # and model_fields_set contains the field
        if self.tax_office is None and "tax_office" in self.model_fields_set:
            _dict['taxOffice'] = None

        # set to None if total_invoices (nullable) is None
        # and model_fields_set contains the field
        if self.total_invoices is None and "total_invoices" in self.model_fields_set:
            _dict['totalInvoices'] = None

        # set to None if total_revenue (nullable) is None
        # and model_fields_set contains the field
        if self.total_revenue is None and "total_revenue" in self.model_fields_set:
            _dict['totalRevenue'] = None

        # set to None if vat_id (nullable) is None
        # and model_fields_set contains the field
        if self.vat_id is None and "vat_id" in self.model_fields_set:
            _dict['vatId'] = None

        # set to None if vat_id_validated (nullable) is None
        # and model_fields_set contains the field
        if self.vat_id_validated is None and "vat_id_validated" in self.model_fields_set:
            _dict['vatIdValidated'] = None

        # set to None if vat_id_validation_date (nullable) is None
        # and model_fields_set contains the field
        if self.vat_id_validation_date is None and "vat_id_validation_date" in self.model_fields_set:
            _dict['vatIdValidationDate'] = None

        # set to None if website (nullable) is None
        # and model_fields_set contains the field
        if self.website is None and "website" in self.model_fields_set:
            _dict['website'] = None

        # set to None if zip (nullable) is None
        # and model_fields_set contains the field
        if self.zip is None and "zip" in self.model_fields_set:
            _dict['zip'] = None

        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of ContactUpdate from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "accountHolder": obj.get("accountHolder"),
            "acquisitionCost": obj.get("acquisitionCost"),
            "addressSupplement": obj.get("addressSupplement"),
            "attention": obj.get("attention"),
            "bankName": obj.get("bankName"),
            "bic": obj.get("bic"),
            "buyerReference": obj.get("buyerReference"),
            "category": obj.get("category"),
            "certificateAuthority": obj.get("certificateAuthority"),
            "certificateNumber": obj.get("certificateNumber"),
            "certificateParagraph": obj.get("certificateParagraph"),
            "certificateValidUntil": obj.get("certificateValidUntil"),
            "city": obj.get("city"),
            "companyName": obj.get("companyName"),
            "contactPersons": obj.get("contactPersons"),
            "contactType": obj.get("contactType"),
            "country": obj.get("country"),
            "creditLimit": obj.get("creditLimit"),
            "creditorAccountSkr03": obj.get("creditorAccountSkr03"),
            "creditorAccountSkr04": obj.get("creditorAccountSkr04"),
            "currency": obj.get("currency"),
            "customFields": obj.get("customFields"),
            "customerNumber": obj.get("customerNumber"),
            "debitorAccountSkr03": obj.get("debitorAccountSkr03"),
            "debitorAccountSkr04": obj.get("debitorAccountSkr04"),
            "defaultDebitorNumber": obj.get("defaultDebitorNumber"),
            "deliveryBlock": obj.get("deliveryBlock"),
            "department": obj.get("department"),
            "discountDays": obj.get("discountDays"),
            "discountPercentage": obj.get("discountPercentage"),
            "donationReceiptEligible": obj.get("donationReceiptEligible"),
            "email": obj.get("email"),
            "externalId": obj.get("externalId"),
            "fax": obj.get("fax"),
            "iban": obj.get("iban"),
            "industry": obj.get("industry"),
            "isActive": obj.get("isActive"),
            "isMember": obj.get("isMember"),
            "isNonprofit": obj.get("isNonprofit"),
            "lastContactDate": obj.get("lastContactDate"),
            "lastPurchaseDate": obj.get("lastPurchaseDate"),
            "leitwegId": obj.get("leitwegId"),
            "lifetimeValue": obj.get("lifetimeValue"),
            "mandateDate": obj.get("mandateDate"),
            "mandateReference": obj.get("mandateReference"),
            "marketingConsent": obj.get("marketingConsent"),
            "marketingConsentAt": obj.get("marketingConsentAt"),
            "marketingConsentSource": obj.get("marketingConsentSource"),
            "mobile": obj.get("mobile"),
            "name": obj.get("name"),
            "nextContactDate": obj.get("nextContactDate"),
            "notes": obj.get("notes"),
            "openingBalance": obj.get("openingBalance"),
            "openingBalanceDate": obj.get("openingBalanceDate"),
            "orderReference": obj.get("orderReference"),
            "paymentBlock": obj.get("paymentBlock"),
            "paymentGracePeriodDays": obj.get("paymentGracePeriodDays"),
            "paymentMethods": obj.get("paymentMethods"),
            "paymentTerms": obj.get("paymentTerms"),
            "phone": obj.get("phone"),
            "rating": obj.get("rating"),
            "salesRepresentative": obj.get("salesRepresentative"),
            "sepaBatchBooking": obj.get("sepaBatchBooking"),
            "sepaSequenceType": obj.get("sepaSequenceType"),
            "socialMedia": obj.get("socialMedia"),
            "source": obj.get("source"),
            "state": obj.get("state"),
            "street": obj.get("street"),
            "streetNumber": obj.get("streetNumber"),
            "supplierNumber": obj.get("supplierNumber"),
            "tags": obj.get("tags"),
            "taxCountry": obj.get("taxCountry"),
            "taxNumber": obj.get("taxNumber"),
            "taxOffice": obj.get("taxOffice"),
            "totalInvoices": obj.get("totalInvoices"),
            "totalRevenue": obj.get("totalRevenue"),
            "vatId": obj.get("vatId"),
            "vatIdValidated": obj.get("vatIdValidated"),
            "vatIdValidationDate": obj.get("vatIdValidationDate"),
            "website": obj.get("website"),
            "zip": obj.get("zip")
        })
        return _obj


