# coding: utf-8

"""
    SimpleBilly API

    Simplebilly API - Bookkeeping, CRM, ERP. Multi-tenant API: a tenant is isolated and routed by subdomain (or a configured custom domain) under the base domain.  ## Rate limiting All endpoints are rate-limited per client IP: **100 requests per minute** on API routes and **5 requests per minute** on authentication routes. Exceeding a limit returns `429 Too Many Requests`; the window resets after 60 seconds.

    The version of the OpenAPI document: 0.1.0
    Contact: support@simplebilly.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict, Field, StrictInt, StrictStr
from typing import Any, ClassVar, Dict, List, Optional
from uuid import UUID
from typing import Optional, Set
from typing_extensions import Self
from pydantic_core import to_jsonable_python

class CostingLine(BaseModel):
    """
    A single costing line: material cost for one BOM component.
    """ # noqa: E501
    line_cost: StrictStr = Field(description="total_quantity × unit_purchase_price (0 when price unknown).", alias="lineCost")
    name: StrictStr
    product_id: UUID = Field(alias="productId")
    quantity_per_unit: StrictInt = Field(description="Component quantity required per finished unit.", alias="quantityPerUnit")
    sku: StrictStr
    total_quantity: StrictInt = Field(description="Total component quantity consumed by this order.", alias="totalQuantity")
    unit_purchase_price: Optional[StrictStr] = Field(default=None, alias="unitPurchasePrice")
    __properties: ClassVar[List[str]] = ["lineCost", "name", "productId", "quantityPerUnit", "sku", "totalQuantity", "unitPurchasePrice"]

    model_config = ConfigDict(
        validate_by_name=True,
        validate_by_alias=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        return json.dumps(to_jsonable_python(self.to_dict()))

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of CostingLine from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # set to None if unit_purchase_price (nullable) is None
        # and model_fields_set contains the field
        if self.unit_purchase_price is None and "unit_purchase_price" in self.model_fields_set:
            _dict['unitPurchasePrice'] = None

        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of CostingLine from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "lineCost": obj.get("lineCost"),
            "name": obj.get("name"),
            "productId": obj.get("productId"),
            "quantityPerUnit": obj.get("quantityPerUnit"),
            "sku": obj.get("sku"),
            "totalQuantity": obj.get("totalQuantity"),
            "unitPurchasePrice": obj.get("unitPurchasePrice")
        })
        return _obj


