# coding: utf-8

"""
    SimpleBilly API

    Simplebilly API - Bookkeeping, CRM, ERP. Multi-tenant API: a tenant is isolated and routed by subdomain (or a configured custom domain) under the base domain.  ## Rate limiting All endpoints are rate-limited per client IP: **100 requests per minute** on API routes and **5 requests per minute** on authentication routes. Exceeding a limit returns `429 Too Many Requests`; the window resets after 60 seconds.

    The version of the OpenAPI document: 0.1.0
    Contact: support@simplebilly.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from datetime import date
from pydantic import BaseModel, ConfigDict, Field, StrictStr
from typing import Any, ClassVar, Dict, List, Optional
from simplebilly_api.models.preceding_sales_voucher_type import PrecedingSalesVoucherType
from simplebilly_api.models.voucher_status import VoucherStatus
from typing import Optional, Set
from typing_extensions import Self
from pydantic_core import to_jsonable_python

class DeliveryNote(BaseModel):
    """
    DeliveryNote
    """ # noqa: E501
    address: Optional[Any] = None
    contact_id: Optional[StrictStr] = Field(default=None, description="References the contact entity.", alias="contactId")
    contact_name: Optional[StrictStr] = Field(default=None, alias="contactName")
    currency: StrictStr
    delivery_date: Optional[date] = Field(default=None, alias="deliveryDate")
    delivery_note_number: Optional[StrictStr] = Field(default=None, alias="deliveryNoteNumber")
    files: Optional[Any] = None
    introduction: Optional[StrictStr] = None
    line_items: Optional[Any] = Field(default=None, alias="lineItems")
    preceding_sales_voucher_id: Optional[StrictStr] = Field(default=None, description="References the preceding sales voucher entity.", alias="precedingSalesVoucherId")
    preceding_sales_voucher_type: Optional[PrecedingSalesVoucherType] = Field(default=None, alias="precedingSalesVoucherType")
    remark: Optional[StrictStr] = None
    shipping_date: Optional[date] = Field(default=None, alias="shippingDate")
    shipping_method: Optional[StrictStr] = Field(default=None, alias="shippingMethod")
    subtotal: Optional[StrictStr] = None
    title: Optional[StrictStr] = None
    total_amount: Optional[StrictStr] = Field(default=None, alias="totalAmount")
    voucher_date: date = Field(alias="voucherDate")
    voucher_status: VoucherStatus = Field(alias="voucherStatus")
    __properties: ClassVar[List[str]] = ["address", "contactId", "contactName", "currency", "deliveryDate", "deliveryNoteNumber", "files", "introduction", "lineItems", "precedingSalesVoucherId", "precedingSalesVoucherType", "remark", "shippingDate", "shippingMethod", "subtotal", "title", "totalAmount", "voucherDate", "voucherStatus"]

    model_config = ConfigDict(
        validate_by_name=True,
        validate_by_alias=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        return json.dumps(to_jsonable_python(self.to_dict()))

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of DeliveryNote from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # set to None if address (nullable) is None
        # and model_fields_set contains the field
        if self.address is None and "address" in self.model_fields_set:
            _dict['address'] = None

        # set to None if contact_id (nullable) is None
        # and model_fields_set contains the field
        if self.contact_id is None and "contact_id" in self.model_fields_set:
            _dict['contactId'] = None

        # set to None if contact_name (nullable) is None
        # and model_fields_set contains the field
        if self.contact_name is None and "contact_name" in self.model_fields_set:
            _dict['contactName'] = None

        # set to None if delivery_date (nullable) is None
        # and model_fields_set contains the field
        if self.delivery_date is None and "delivery_date" in self.model_fields_set:
            _dict['deliveryDate'] = None

        # set to None if delivery_note_number (nullable) is None
        # and model_fields_set contains the field
        if self.delivery_note_number is None and "delivery_note_number" in self.model_fields_set:
            _dict['deliveryNoteNumber'] = None

        # set to None if files (nullable) is None
        # and model_fields_set contains the field
        if self.files is None and "files" in self.model_fields_set:
            _dict['files'] = None

        # set to None if introduction (nullable) is None
        # and model_fields_set contains the field
        if self.introduction is None and "introduction" in self.model_fields_set:
            _dict['introduction'] = None

        # set to None if line_items (nullable) is None
        # and model_fields_set contains the field
        if self.line_items is None and "line_items" in self.model_fields_set:
            _dict['lineItems'] = None

        # set to None if preceding_sales_voucher_id (nullable) is None
        # and model_fields_set contains the field
        if self.preceding_sales_voucher_id is None and "preceding_sales_voucher_id" in self.model_fields_set:
            _dict['precedingSalesVoucherId'] = None

        # set to None if preceding_sales_voucher_type (nullable) is None
        # and model_fields_set contains the field
        if self.preceding_sales_voucher_type is None and "preceding_sales_voucher_type" in self.model_fields_set:
            _dict['precedingSalesVoucherType'] = None

        # set to None if remark (nullable) is None
        # and model_fields_set contains the field
        if self.remark is None and "remark" in self.model_fields_set:
            _dict['remark'] = None

        # set to None if shipping_date (nullable) is None
        # and model_fields_set contains the field
        if self.shipping_date is None and "shipping_date" in self.model_fields_set:
            _dict['shippingDate'] = None

        # set to None if shipping_method (nullable) is None
        # and model_fields_set contains the field
        if self.shipping_method is None and "shipping_method" in self.model_fields_set:
            _dict['shippingMethod'] = None

        # set to None if subtotal (nullable) is None
        # and model_fields_set contains the field
        if self.subtotal is None and "subtotal" in self.model_fields_set:
            _dict['subtotal'] = None

        # set to None if title (nullable) is None
        # and model_fields_set contains the field
        if self.title is None and "title" in self.model_fields_set:
            _dict['title'] = None

        # set to None if total_amount (nullable) is None
        # and model_fields_set contains the field
        if self.total_amount is None and "total_amount" in self.model_fields_set:
            _dict['totalAmount'] = None

        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of DeliveryNote from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "address": obj.get("address"),
            "contactId": obj.get("contactId"),
            "contactName": obj.get("contactName"),
            "currency": obj.get("currency"),
            "deliveryDate": obj.get("deliveryDate"),
            "deliveryNoteNumber": obj.get("deliveryNoteNumber"),
            "files": obj.get("files"),
            "introduction": obj.get("introduction"),
            "lineItems": obj.get("lineItems"),
            "precedingSalesVoucherId": obj.get("precedingSalesVoucherId"),
            "precedingSalesVoucherType": obj.get("precedingSalesVoucherType"),
            "remark": obj.get("remark"),
            "shippingDate": obj.get("shippingDate"),
            "shippingMethod": obj.get("shippingMethod"),
            "subtotal": obj.get("subtotal"),
            "title": obj.get("title"),
            "totalAmount": obj.get("totalAmount"),
            "voucherDate": obj.get("voucherDate"),
            "voucherStatus": obj.get("voucherStatus")
        })
        return _obj


