# coding: utf-8

"""
    SimpleBilly API

    Simplebilly API - Bookkeeping, CRM, ERP. Multi-tenant API: a tenant is isolated and routed by subdomain (or a configured custom domain) under the base domain.  ## Rate limiting All endpoints are rate-limited per client IP: **100 requests per minute** on API routes and **5 requests per minute** on authentication routes. Exceeding a limit returns `429 Too Many Requests`; the window resets after 60 seconds.

    The version of the OpenAPI document: 0.1.0
    Contact: support@simplebilly.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict, StrictStr
from typing import Any, ClassVar, Dict, List
from simplebilly_api.models.account_overview import AccountOverview
from simplebilly_api.models.balance_sheet import BalanceSheet
from simplebilly_api.models.income_statement import IncomeStatement
from simplebilly_api.models.vat_summary import VatSummary
from typing import Optional, Set
from typing_extensions import Self
from pydantic_core import to_jsonable_python

class EBilanzReport(BaseModel):
    """
    EBilanzReport
    """ # noqa: E501
    account_overview: List[AccountOverview]
    balance_sheet: BalanceSheet
    generated_at: StrictStr
    income_statement: IncomeStatement
    period: StrictStr
    vat_summary: VatSummary
    __properties: ClassVar[List[str]] = ["account_overview", "balance_sheet", "generated_at", "income_statement", "period", "vat_summary"]

    model_config = ConfigDict(
        validate_by_name=True,
        validate_by_alias=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        return json.dumps(to_jsonable_python(self.to_dict()))

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of EBilanzReport from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # override the default output from pydantic by calling `to_dict()` of each item in account_overview (list)
        _items = []
        if self.account_overview:
            for _item_account_overview in self.account_overview:
                _items.append(_item_account_overview.to_dict() if _item_account_overview is not None else None)
            _dict['account_overview'] = _items
        # override the default output from pydantic by calling `to_dict()` of balance_sheet
        if self.balance_sheet:
            _dict['balance_sheet'] = self.balance_sheet.to_dict()
        # override the default output from pydantic by calling `to_dict()` of income_statement
        if self.income_statement:
            _dict['income_statement'] = self.income_statement.to_dict()
        # override the default output from pydantic by calling `to_dict()` of vat_summary
        if self.vat_summary:
            _dict['vat_summary'] = self.vat_summary.to_dict()
        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of EBilanzReport from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "account_overview": [AccountOverview.from_dict(_item) for _item in obj["account_overview"]] if obj.get("account_overview") is not None else None,
            "balance_sheet": BalanceSheet.from_dict(obj["balance_sheet"]) if obj.get("balance_sheet") is not None else None,
            "generated_at": obj.get("generated_at"),
            "income_statement": IncomeStatement.from_dict(obj["income_statement"]) if obj.get("income_statement") is not None else None,
            "period": obj.get("period"),
            "vat_summary": VatSummary.from_dict(obj["vat_summary"]) if obj.get("vat_summary") is not None else None
        })
        return _obj


