# coding: utf-8

"""
    SimpleBilly API

    Simplebilly API - Bookkeeping, CRM, ERP. Multi-tenant API: a tenant is isolated and routed by subdomain (or a configured custom domain) under the base domain.  ## Rate limiting All endpoints are rate-limited per client IP: **100 requests per minute** on API routes and **5 requests per minute** on authentication routes. Exceeding a limit returns `429 Too Many Requests`; the window resets after 60 seconds.

    The version of the OpenAPI document: 0.1.0
    Contact: support@simplebilly.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict, Field, StrictInt
from typing import Any, ClassVar, Dict, List, Optional
from typing import Optional, Set
from typing_extensions import Self
from pydantic_core import to_jsonable_python

class InstituteDeadlines(BaseModel):
    """
    InstituteDeadlines
    """ # noqa: E501
    abschlusspruefung_months: Optional[StrictInt] = Field(default=None, description="HGB § 340k/§ 341k: Abschlussprüfung (5 Monate).", alias="abschlusspruefungMonths")
    jahresabschluss_bafin_months: Optional[StrictInt] = Field(default=None, description="KWG § 26: Jahresabschluss an die BaFin (3 Monate, nur KWG-Institute).", alias="jahresabschlussBafinMonths")
    offenlegung_months: StrictInt = Field(description="HGB § 325 Abs. 4: Offenlegung (4 kapitalmarktorientiert / 12 sonst).", alias="offenlegungMonths")
    __properties: ClassVar[List[str]] = ["abschlusspruefungMonths", "jahresabschlussBafinMonths", "offenlegungMonths"]

    model_config = ConfigDict(
        validate_by_name=True,
        validate_by_alias=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        return json.dumps(to_jsonable_python(self.to_dict()))

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of InstituteDeadlines from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # set to None if abschlusspruefung_months (nullable) is None
        # and model_fields_set contains the field
        if self.abschlusspruefung_months is None and "abschlusspruefung_months" in self.model_fields_set:
            _dict['abschlusspruefungMonths'] = None

        # set to None if jahresabschluss_bafin_months (nullable) is None
        # and model_fields_set contains the field
        if self.jahresabschluss_bafin_months is None and "jahresabschluss_bafin_months" in self.model_fields_set:
            _dict['jahresabschlussBafinMonths'] = None

        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of InstituteDeadlines from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "abschlusspruefungMonths": obj.get("abschlusspruefungMonths"),
            "jahresabschlussBafinMonths": obj.get("jahresabschlussBafinMonths"),
            "offenlegungMonths": obj.get("offenlegungMonths")
        })
        return _obj


