# coding: utf-8

"""
    SimpleBilly API

    Simplebilly API - Bookkeeping, CRM, ERP. Multi-tenant API: a tenant is isolated and routed by subdomain (or a configured custom domain) under the base domain.  ## Rate limiting All endpoints are rate-limited per client IP: **100 requests per minute** on API routes and **5 requests per minute** on authentication routes. Exceeding a limit returns `429 Too Many Requests`; the window resets after 60 seconds.

    The version of the OpenAPI document: 0.1.0
    Contact: support@simplebilly.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict, Field, StrictInt, StrictStr
from typing import Any, ClassVar, Dict, List, Optional
from uuid import UUID
from simplebilly_api.models.application_status import ApplicationStatus
from typing import Optional, Set
from typing_extensions import Self
from pydantic_core import to_jsonable_python

class JobApplication(BaseModel):
    """
    JobApplication
    """ # noqa: E501
    cv_file: Optional[StrictStr] = Field(default=None, description="Relative path of the stored CV file under the upload dir.", alias="cvFile")
    cv_text: Optional[StrictStr] = Field(default=None, description="Extracted CV text, used for match-scoring.", alias="cvText")
    email: Optional[StrictStr] = None
    match_reason: Optional[StrictStr] = Field(default=None, alias="matchReason")
    match_score: Optional[StrictInt] = Field(default=None, description="0-100 LLM match score against the posting's required profile.", alias="matchScore")
    name: Optional[StrictStr] = None
    phone: Optional[StrictStr] = None
    posting_id: Optional[UUID] = Field(default=None, description="References the job_posting entity.", alias="postingId")
    source: StrictStr = Field(description="website | email | board")
    status: ApplicationStatus = Field(description="new | reviewing | interview | hired | rejected")
    __properties: ClassVar[List[str]] = ["cvFile", "cvText", "email", "matchReason", "matchScore", "name", "phone", "postingId", "source", "status"]

    model_config = ConfigDict(
        validate_by_name=True,
        validate_by_alias=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        return json.dumps(to_jsonable_python(self.to_dict()))

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of JobApplication from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # set to None if cv_file (nullable) is None
        # and model_fields_set contains the field
        if self.cv_file is None and "cv_file" in self.model_fields_set:
            _dict['cvFile'] = None

        # set to None if cv_text (nullable) is None
        # and model_fields_set contains the field
        if self.cv_text is None and "cv_text" in self.model_fields_set:
            _dict['cvText'] = None

        # set to None if email (nullable) is None
        # and model_fields_set contains the field
        if self.email is None and "email" in self.model_fields_set:
            _dict['email'] = None

        # set to None if match_reason (nullable) is None
        # and model_fields_set contains the field
        if self.match_reason is None and "match_reason" in self.model_fields_set:
            _dict['matchReason'] = None

        # set to None if match_score (nullable) is None
        # and model_fields_set contains the field
        if self.match_score is None and "match_score" in self.model_fields_set:
            _dict['matchScore'] = None

        # set to None if name (nullable) is None
        # and model_fields_set contains the field
        if self.name is None and "name" in self.model_fields_set:
            _dict['name'] = None

        # set to None if phone (nullable) is None
        # and model_fields_set contains the field
        if self.phone is None and "phone" in self.model_fields_set:
            _dict['phone'] = None

        # set to None if posting_id (nullable) is None
        # and model_fields_set contains the field
        if self.posting_id is None and "posting_id" in self.model_fields_set:
            _dict['postingId'] = None

        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of JobApplication from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "cvFile": obj.get("cvFile"),
            "cvText": obj.get("cvText"),
            "email": obj.get("email"),
            "matchReason": obj.get("matchReason"),
            "matchScore": obj.get("matchScore"),
            "name": obj.get("name"),
            "phone": obj.get("phone"),
            "postingId": obj.get("postingId"),
            "source": obj.get("source"),
            "status": obj.get("status")
        })
        return _obj


