# coding: utf-8

"""
    SimpleBilly API

    Simplebilly API - Bookkeeping, CRM, ERP. Multi-tenant API: a tenant is isolated and routed by subdomain (or a configured custom domain) under the base domain.  ## Rate limiting All endpoints are rate-limited per client IP: **100 requests per minute** on API routes and **5 requests per minute** on authentication routes. Exceeding a limit returns `429 Too Many Requests`; the window resets after 60 seconds.

    The version of the OpenAPI document: 0.1.0
    Contact: support@simplebilly.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict, StrictBool, StrictInt, StrictStr
from typing import Any, ClassVar, Dict, List, Optional
from typing import Optional, Set
from typing_extensions import Self
from pydantic_core import to_jsonable_python

class PackingQueueItem(BaseModel):
    """
    PackingQueueItem
    """ # noqa: E501
    created_at: StrictStr
    customer_id: StrictStr
    delivery_note_printed: StrictBool
    items: Optional[Any]
    items_count: StrictInt
    label_printed: StrictBool
    order_number: StrictStr
    order_status: StrictStr
    shipment_id: Optional[StrictStr] = None
    shipping_address: Optional[Any] = None
    shipping_method: StrictStr
    tracking_number: Optional[StrictStr] = None
    video_recording: Optional[StrictStr] = None
    __properties: ClassVar[List[str]] = ["created_at", "customer_id", "delivery_note_printed", "items", "items_count", "label_printed", "order_number", "order_status", "shipment_id", "shipping_address", "shipping_method", "tracking_number", "video_recording"]

    model_config = ConfigDict(
        validate_by_name=True,
        validate_by_alias=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        return json.dumps(to_jsonable_python(self.to_dict()))

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of PackingQueueItem from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # set to None if items (nullable) is None
        # and model_fields_set contains the field
        if self.items is None and "items" in self.model_fields_set:
            _dict['items'] = None

        # set to None if shipment_id (nullable) is None
        # and model_fields_set contains the field
        if self.shipment_id is None and "shipment_id" in self.model_fields_set:
            _dict['shipment_id'] = None

        # set to None if shipping_address (nullable) is None
        # and model_fields_set contains the field
        if self.shipping_address is None and "shipping_address" in self.model_fields_set:
            _dict['shipping_address'] = None

        # set to None if tracking_number (nullable) is None
        # and model_fields_set contains the field
        if self.tracking_number is None and "tracking_number" in self.model_fields_set:
            _dict['tracking_number'] = None

        # set to None if video_recording (nullable) is None
        # and model_fields_set contains the field
        if self.video_recording is None and "video_recording" in self.model_fields_set:
            _dict['video_recording'] = None

        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of PackingQueueItem from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "created_at": obj.get("created_at"),
            "customer_id": obj.get("customer_id"),
            "delivery_note_printed": obj.get("delivery_note_printed"),
            "items": obj.get("items"),
            "items_count": obj.get("items_count"),
            "label_printed": obj.get("label_printed"),
            "order_number": obj.get("order_number"),
            "order_status": obj.get("order_status"),
            "shipment_id": obj.get("shipment_id"),
            "shipping_address": obj.get("shipping_address"),
            "shipping_method": obj.get("shipping_method"),
            "tracking_number": obj.get("tracking_number"),
            "video_recording": obj.get("video_recording")
        })
        return _obj


