# coding: utf-8

"""
    SimpleBilly API

    Simplebilly API - Bookkeeping, CRM, ERP. Multi-tenant API: a tenant is isolated and routed by subdomain (or a configured custom domain) under the base domain.  ## Rate limiting All endpoints are rate-limited per client IP: **100 requests per minute** on API routes and **5 requests per minute** on authentication routes. Exceeding a limit returns `429 Too Many Requests`; the window resets after 60 seconds.

    The version of the OpenAPI document: 0.1.0
    Contact: support@simplebilly.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from datetime import datetime
from pydantic import BaseModel, ConfigDict, Field, StrictBool, StrictInt, StrictStr
from typing import Any, ClassVar, Dict, List, Optional
from simplebilly_api.models.posting_category_type import PostingCategoryType
from typing import Optional, Set
from typing_extensions import Self
from pydantic_core import to_jsonable_python

class PostingCategoryCreate(BaseModel):
    """
    PostingCategoryCreate
    """ # noqa: E501
    account_number: Optional[StrictStr] = Field(default=None, alias="accountNumber")
    account_number_skr03: Optional[StrictStr] = Field(default=None, alias="accountNumberSkr03")
    account_number_skr04: Optional[StrictStr] = Field(default=None, alias="accountNumberSkr04")
    account_number_skr49: Optional[StrictStr] = Field(default=None, alias="accountNumberSkr49")
    category_type: PostingCategoryType = Field(alias="categoryType")
    created_at: datetime = Field(alias="createdAt")
    default_vat_rate: StrictInt = Field(alias="defaultVatRate")
    description: Optional[StrictStr] = None
    eks_category: Optional[StrictStr] = Field(default=None, alias="eksCategory")
    eu_vat_line: Optional[StrictInt] = Field(default=None, alias="euVatLine")
    input_vat_percentage: StrictStr = Field(alias="inputVatPercentage")
    is_active: StrictBool = Field(alias="isActive")
    is_system: StrictBool = Field(alias="isSystem")
    name: StrictStr
    skr_version: StrictStr = Field(alias="skrVersion")
    updated_at: Optional[datetime] = Field(default=None, alias="updatedAt")
    user_modified_skr03: StrictBool = Field(alias="userModifiedSkr03")
    user_modified_skr04: StrictBool = Field(alias="userModifiedSkr04")
    __properties: ClassVar[List[str]] = ["accountNumber", "accountNumberSkr03", "accountNumberSkr04", "accountNumberSkr49", "categoryType", "createdAt", "defaultVatRate", "description", "eksCategory", "euVatLine", "inputVatPercentage", "isActive", "isSystem", "name", "skrVersion", "updatedAt", "userModifiedSkr03", "userModifiedSkr04"]

    model_config = ConfigDict(
        validate_by_name=True,
        validate_by_alias=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        return json.dumps(to_jsonable_python(self.to_dict()))

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of PostingCategoryCreate from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # set to None if account_number (nullable) is None
        # and model_fields_set contains the field
        if self.account_number is None and "account_number" in self.model_fields_set:
            _dict['accountNumber'] = None

        # set to None if account_number_skr03 (nullable) is None
        # and model_fields_set contains the field
        if self.account_number_skr03 is None and "account_number_skr03" in self.model_fields_set:
            _dict['accountNumberSkr03'] = None

        # set to None if account_number_skr04 (nullable) is None
        # and model_fields_set contains the field
        if self.account_number_skr04 is None and "account_number_skr04" in self.model_fields_set:
            _dict['accountNumberSkr04'] = None

        # set to None if account_number_skr49 (nullable) is None
        # and model_fields_set contains the field
        if self.account_number_skr49 is None and "account_number_skr49" in self.model_fields_set:
            _dict['accountNumberSkr49'] = None

        # set to None if description (nullable) is None
        # and model_fields_set contains the field
        if self.description is None and "description" in self.model_fields_set:
            _dict['description'] = None

        # set to None if eks_category (nullable) is None
        # and model_fields_set contains the field
        if self.eks_category is None and "eks_category" in self.model_fields_set:
            _dict['eksCategory'] = None

        # set to None if eu_vat_line (nullable) is None
        # and model_fields_set contains the field
        if self.eu_vat_line is None and "eu_vat_line" in self.model_fields_set:
            _dict['euVatLine'] = None

        # set to None if updated_at (nullable) is None
        # and model_fields_set contains the field
        if self.updated_at is None and "updated_at" in self.model_fields_set:
            _dict['updatedAt'] = None

        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of PostingCategoryCreate from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "accountNumber": obj.get("accountNumber"),
            "accountNumberSkr03": obj.get("accountNumberSkr03"),
            "accountNumberSkr04": obj.get("accountNumberSkr04"),
            "accountNumberSkr49": obj.get("accountNumberSkr49"),
            "categoryType": obj.get("categoryType"),
            "createdAt": obj.get("createdAt"),
            "defaultVatRate": obj.get("defaultVatRate"),
            "description": obj.get("description"),
            "eksCategory": obj.get("eksCategory"),
            "euVatLine": obj.get("euVatLine"),
            "inputVatPercentage": obj.get("inputVatPercentage"),
            "isActive": obj.get("isActive"),
            "isSystem": obj.get("isSystem"),
            "name": obj.get("name"),
            "skrVersion": obj.get("skrVersion"),
            "updatedAt": obj.get("updatedAt"),
            "userModifiedSkr03": obj.get("userModifiedSkr03"),
            "userModifiedSkr04": obj.get("userModifiedSkr04")
        })
        return _obj


