# coding: utf-8

"""
    SimpleBilly API

    Simplebilly API - Bookkeeping, CRM, ERP. Multi-tenant API: a tenant is isolated and routed by subdomain (or a configured custom domain) under the base domain.  ## Rate limiting All endpoints are rate-limited per client IP: **100 requests per minute** on API routes and **5 requests per minute** on authentication routes. Exceeding a limit returns `429 Too Many Requests`; the window resets after 60 seconds.

    The version of the OpenAPI document: 0.1.0
    Contact: support@simplebilly.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from datetime import date
from pydantic import BaseModel, ConfigDict, Field, StrictInt, StrictStr
from typing import Any, ClassVar, Dict, List, Optional
from uuid import UUID
from simplebilly_api.models.production_order_status import ProductionOrderStatus
from typing import Optional, Set
from typing_extensions import Self
from pydantic_core import to_jsonable_python

class ProductionOrder(BaseModel):
    """
    ProductionOrder
    """ # noqa: E501
    bom_id: Optional[UUID] = Field(default=None, description="References the BOM entity.", alias="bomId")
    components: Optional[Any] = Field(default=None, description="JSON snapshot of the BOM components at creation time.")
    end_date: Optional[date] = Field(default=None, alias="endDate")
    notes: Optional[StrictStr] = None
    order_number: StrictStr = Field(alias="orderNumber")
    product_id: UUID = Field(description="The finished product to manufacture. References the product entity.", alias="productId")
    quantity: StrictInt = Field(description="Quantity of finished product to produce.")
    source_warehouse_id: Optional[StrictStr] = Field(default=None, description="Warehouse components are consumed from. References the warehouse entity.", alias="sourceWarehouseId")
    start_date: Optional[date] = Field(default=None, alias="startDate")
    status: Optional[ProductionOrderStatus] = Field(default=None, description="One of: planned | in_production | completed | cancelled")
    target_warehouse_id: Optional[StrictStr] = Field(default=None, description="Warehouse the finished product is added to. References the warehouse entity.", alias="targetWarehouseId")
    __properties: ClassVar[List[str]] = ["bomId", "components", "endDate", "notes", "orderNumber", "productId", "quantity", "sourceWarehouseId", "startDate", "status", "targetWarehouseId"]

    model_config = ConfigDict(
        validate_by_name=True,
        validate_by_alias=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        return json.dumps(to_jsonable_python(self.to_dict()))

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of ProductionOrder from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # set to None if bom_id (nullable) is None
        # and model_fields_set contains the field
        if self.bom_id is None and "bom_id" in self.model_fields_set:
            _dict['bomId'] = None

        # set to None if components (nullable) is None
        # and model_fields_set contains the field
        if self.components is None and "components" in self.model_fields_set:
            _dict['components'] = None

        # set to None if end_date (nullable) is None
        # and model_fields_set contains the field
        if self.end_date is None and "end_date" in self.model_fields_set:
            _dict['endDate'] = None

        # set to None if notes (nullable) is None
        # and model_fields_set contains the field
        if self.notes is None and "notes" in self.model_fields_set:
            _dict['notes'] = None

        # set to None if source_warehouse_id (nullable) is None
        # and model_fields_set contains the field
        if self.source_warehouse_id is None and "source_warehouse_id" in self.model_fields_set:
            _dict['sourceWarehouseId'] = None

        # set to None if start_date (nullable) is None
        # and model_fields_set contains the field
        if self.start_date is None and "start_date" in self.model_fields_set:
            _dict['startDate'] = None

        # set to None if target_warehouse_id (nullable) is None
        # and model_fields_set contains the field
        if self.target_warehouse_id is None and "target_warehouse_id" in self.model_fields_set:
            _dict['targetWarehouseId'] = None

        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of ProductionOrder from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "bomId": obj.get("bomId"),
            "components": obj.get("components"),
            "endDate": obj.get("endDate"),
            "notes": obj.get("notes"),
            "orderNumber": obj.get("orderNumber"),
            "productId": obj.get("productId"),
            "quantity": obj.get("quantity"),
            "sourceWarehouseId": obj.get("sourceWarehouseId"),
            "startDate": obj.get("startDate"),
            "status": obj.get("status"),
            "targetWarehouseId": obj.get("targetWarehouseId")
        })
        return _obj


