# coding: utf-8

"""
    SimpleBilly API

    Simplebilly API - Bookkeeping, CRM, ERP. Multi-tenant API: a tenant is isolated and routed by subdomain (or a configured custom domain) under the base domain.  ## Rate limiting All endpoints are rate-limited per client IP: **100 requests per minute** on API routes and **5 requests per minute** on authentication routes. Exceeding a limit returns `429 Too Many Requests`; the window resets after 60 seconds.

    The version of the OpenAPI document: 0.1.0
    Contact: support@simplebilly.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict, Field, StrictInt, StrictStr
from typing import Any, ClassVar, Dict, List, Optional
from simplebilly_api.models.quota_override_features import QuotaOverrideFeatures
from typing import Optional, Set
from typing_extensions import Self
from pydantic_core import to_jsonable_python

class QuotaOverride(BaseModel):
    """
    Schema of the `tenants.quotas` JSON override column. Any field that is present overrides the plan-derived value.
    """ # noqa: E501
    features: Optional[QuotaOverrideFeatures] = None
    max_connectors: Optional[StrictInt] = None
    max_invoices_per_month: Optional[StrictInt] = None
    max_users: Optional[StrictInt] = None
    metered: Optional[Dict[str, StrictInt]] = None
    plan: Optional[StrictStr] = Field(default=None, description="Custom plan id; unknown ids resolve to enterprise limits.")
    __properties: ClassVar[List[str]] = ["features", "max_connectors", "max_invoices_per_month", "max_users", "metered", "plan"]

    model_config = ConfigDict(
        validate_by_name=True,
        validate_by_alias=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        return json.dumps(to_jsonable_python(self.to_dict()))

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of QuotaOverride from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # override the default output from pydantic by calling `to_dict()` of features
        if self.features:
            _dict['features'] = self.features.to_dict()
        # set to None if features (nullable) is None
        # and model_fields_set contains the field
        if self.features is None and "features" in self.model_fields_set:
            _dict['features'] = None

        # set to None if max_connectors (nullable) is None
        # and model_fields_set contains the field
        if self.max_connectors is None and "max_connectors" in self.model_fields_set:
            _dict['max_connectors'] = None

        # set to None if max_invoices_per_month (nullable) is None
        # and model_fields_set contains the field
        if self.max_invoices_per_month is None and "max_invoices_per_month" in self.model_fields_set:
            _dict['max_invoices_per_month'] = None

        # set to None if max_users (nullable) is None
        # and model_fields_set contains the field
        if self.max_users is None and "max_users" in self.model_fields_set:
            _dict['max_users'] = None

        # set to None if metered (nullable) is None
        # and model_fields_set contains the field
        if self.metered is None and "metered" in self.model_fields_set:
            _dict['metered'] = None

        # set to None if plan (nullable) is None
        # and model_fields_set contains the field
        if self.plan is None and "plan" in self.model_fields_set:
            _dict['plan'] = None

        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of QuotaOverride from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "features": QuotaOverrideFeatures.from_dict(obj["features"]) if obj.get("features") is not None else None,
            "max_connectors": obj.get("max_connectors"),
            "max_invoices_per_month": obj.get("max_invoices_per_month"),
            "max_users": obj.get("max_users"),
            "metered": obj.get("metered"),
            "plan": obj.get("plan")
        })
        return _obj


