# coding: utf-8

"""
    SimpleBilly API

    Simplebilly API - Bookkeeping, CRM, ERP. Multi-tenant API: a tenant is isolated and routed by subdomain (or a configured custom domain) under the base domain.  ## Rate limiting All endpoints are rate-limited per client IP: **100 requests per minute** on API routes and **5 requests per minute** on authentication routes. Exceeding a limit returns `429 Too Many Requests`; the window resets after 60 seconds.

    The version of the OpenAPI document: 0.1.0
    Contact: support@simplebilly.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from datetime import datetime
from pydantic import BaseModel, ConfigDict, Field, StrictBool, StrictFloat, StrictInt, StrictStr
from typing import Any, ClassVar, Dict, List, Optional, Union
from simplebilly_api.models.plan_features import PlanFeatures
from simplebilly_api.models.plan_limits import PlanLimits
from simplebilly_api.models.usage_snapshot import UsageSnapshot
from typing import Optional, Set
from typing_extensions import Self
from pydantic_core import to_jsonable_python

class SubscriptionOverview(BaseModel):
    """
    Tenant subscription overview for the billing page: current plan, status, period end, trial state, effective limits, current usage and feature flags. Backed by Paddle Billing webhook data written into `billing_info` + `tenants.plan`, and by the canonical plans in `crate::saasy::plans`.  JSON contract (camelCase, matches the frontend): `plan`, `planName`, `priceEur`, `status`, `currentPeriodEnd`, `manageUrl`, `trialEndsAt`, `isTrialing`, `limits:{maxUsers,maxInvoicesPerMonth,maxConnectors}`, `usage:{users,invoicesThisMonth,connectors,overageSeats}`, `features:{taxAutomations,fancyReports,erp}`.
    """ # noqa: E501
    current_period_end: Optional[datetime] = Field(default=None, alias="currentPeriodEnd")
    features: PlanFeatures
    is_trialing: StrictBool = Field(alias="isTrialing")
    limits: PlanLimits
    manage_url: Optional[StrictStr] = Field(default=None, alias="manageUrl")
    plan: StrictStr = Field(description="Resolved plan id (free/starter/business/enterprise, or a custom override id).")
    plan_name: StrictStr = Field(alias="planName")
    price_eur: Union[StrictFloat, StrictInt] = Field(description="Monthly price in EUR; `-1.0` = custom pricing (enterprise).", alias="priceEur")
    quantity: Optional[StrictInt] = None
    status: Optional[StrictStr] = None
    subscription_id: Optional[StrictStr] = Field(default=None, alias="subscriptionId")
    trial_ends_at: Optional[datetime] = Field(default=None, alias="trialEndsAt")
    usage: UsageSnapshot
    __properties: ClassVar[List[str]] = ["currentPeriodEnd", "features", "isTrialing", "limits", "manageUrl", "plan", "planName", "priceEur", "quantity", "status", "subscriptionId", "trialEndsAt", "usage"]

    model_config = ConfigDict(
        validate_by_name=True,
        validate_by_alias=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        return json.dumps(to_jsonable_python(self.to_dict()))

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of SubscriptionOverview from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # override the default output from pydantic by calling `to_dict()` of features
        if self.features:
            _dict['features'] = self.features.to_dict()
        # override the default output from pydantic by calling `to_dict()` of limits
        if self.limits:
            _dict['limits'] = self.limits.to_dict()
        # override the default output from pydantic by calling `to_dict()` of usage
        if self.usage:
            _dict['usage'] = self.usage.to_dict()
        # set to None if current_period_end (nullable) is None
        # and model_fields_set contains the field
        if self.current_period_end is None and "current_period_end" in self.model_fields_set:
            _dict['currentPeriodEnd'] = None

        # set to None if manage_url (nullable) is None
        # and model_fields_set contains the field
        if self.manage_url is None and "manage_url" in self.model_fields_set:
            _dict['manageUrl'] = None

        # set to None if quantity (nullable) is None
        # and model_fields_set contains the field
        if self.quantity is None and "quantity" in self.model_fields_set:
            _dict['quantity'] = None

        # set to None if status (nullable) is None
        # and model_fields_set contains the field
        if self.status is None and "status" in self.model_fields_set:
            _dict['status'] = None

        # set to None if subscription_id (nullable) is None
        # and model_fields_set contains the field
        if self.subscription_id is None and "subscription_id" in self.model_fields_set:
            _dict['subscriptionId'] = None

        # set to None if trial_ends_at (nullable) is None
        # and model_fields_set contains the field
        if self.trial_ends_at is None and "trial_ends_at" in self.model_fields_set:
            _dict['trialEndsAt'] = None

        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of SubscriptionOverview from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "currentPeriodEnd": obj.get("currentPeriodEnd"),
            "features": PlanFeatures.from_dict(obj["features"]) if obj.get("features") is not None else None,
            "isTrialing": obj.get("isTrialing"),
            "limits": PlanLimits.from_dict(obj["limits"]) if obj.get("limits") is not None else None,
            "manageUrl": obj.get("manageUrl"),
            "plan": obj.get("plan"),
            "planName": obj.get("planName"),
            "priceEur": obj.get("priceEur"),
            "quantity": obj.get("quantity"),
            "status": obj.get("status"),
            "subscriptionId": obj.get("subscriptionId"),
            "trialEndsAt": obj.get("trialEndsAt"),
            "usage": UsageSnapshot.from_dict(obj["usage"]) if obj.get("usage") is not None else None
        })
        return _obj


