# coding: utf-8

"""
    SimpleBilly API

    Simplebilly API - Bookkeeping, CRM, ERP. Multi-tenant API: a tenant is isolated and routed by subdomain (or a configured custom domain) under the base domain.  ## Rate limiting All endpoints are rate-limited per client IP: **100 requests per minute** on API routes and **5 requests per minute** on authentication routes. Exceeding a limit returns `429 Too Many Requests`; the window resets after 60 seconds.

    The version of the OpenAPI document: 0.1.0
    Contact: support@simplebilly.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict, Field, StrictBool, StrictInt, StrictStr
from typing import Any, ClassVar, Dict, List, Optional
from typing_extensions import Annotated
from typing import Optional, Set
from typing_extensions import Self
from pydantic_core import to_jsonable_python

class SupplierConditionCreate(BaseModel):
    """
    SupplierConditionCreate
    """ # noqa: E501
    currency: Annotated[str, Field(min_length=3, strict=True, max_length=3)] = Field(description="Currency for the minimum order value.")
    delivery_terms: Optional[StrictStr] = Field(default=None, description="Incoterms, e.g. \"EXW\", \"DAP\".", alias="deliveryTerms")
    early_payment_discount_percent: Optional[StrictStr] = Field(default=None, description="Early-payment discount percentage (Skonto), e.g. 2.0.", alias="earlyPaymentDiscountPercent")
    is_default: Optional[StrictBool] = Field(default=None, description="Is this the default condition for the supplier?", alias="isDefault")
    minimum_order_value: Optional[StrictStr] = Field(default=None, description="Minimum order value required for this supplier.", alias="minimumOrderValue")
    notes: Optional[StrictStr] = None
    payment_due_days: Optional[StrictInt] = Field(default=None, description="Number of days within which payment is due.", alias="paymentDueDays")
    payment_terms: Optional[StrictStr] = Field(default=None, description="Payment terms, e.g. \"14 Tage, 2% Skonto\".", alias="paymentTerms")
    supplier_contact_id: StrictStr = Field(description="The supplier this condition applies to (`contact_id`). References the supplier entity.", alias="supplierContactId")
    supplier_name: Optional[StrictStr] = Field(default=None, description="The name of the supplier, denormalized for easy listing.", alias="supplierName")
    volume_discount_tiers: Optional[Any] = Field(default=None, description="Tiered discounts: JSON array of `{min_quantity, discount_percent}`.", alias="volumeDiscountTiers")
    __properties: ClassVar[List[str]] = ["currency", "deliveryTerms", "earlyPaymentDiscountPercent", "isDefault", "minimumOrderValue", "notes", "paymentDueDays", "paymentTerms", "supplierContactId", "supplierName", "volumeDiscountTiers"]

    model_config = ConfigDict(
        validate_by_name=True,
        validate_by_alias=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        return json.dumps(to_jsonable_python(self.to_dict()))

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of SupplierConditionCreate from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # set to None if delivery_terms (nullable) is None
        # and model_fields_set contains the field
        if self.delivery_terms is None and "delivery_terms" in self.model_fields_set:
            _dict['deliveryTerms'] = None

        # set to None if early_payment_discount_percent (nullable) is None
        # and model_fields_set contains the field
        if self.early_payment_discount_percent is None and "early_payment_discount_percent" in self.model_fields_set:
            _dict['earlyPaymentDiscountPercent'] = None

        # set to None if minimum_order_value (nullable) is None
        # and model_fields_set contains the field
        if self.minimum_order_value is None and "minimum_order_value" in self.model_fields_set:
            _dict['minimumOrderValue'] = None

        # set to None if notes (nullable) is None
        # and model_fields_set contains the field
        if self.notes is None and "notes" in self.model_fields_set:
            _dict['notes'] = None

        # set to None if payment_due_days (nullable) is None
        # and model_fields_set contains the field
        if self.payment_due_days is None and "payment_due_days" in self.model_fields_set:
            _dict['paymentDueDays'] = None

        # set to None if payment_terms (nullable) is None
        # and model_fields_set contains the field
        if self.payment_terms is None and "payment_terms" in self.model_fields_set:
            _dict['paymentTerms'] = None

        # set to None if supplier_name (nullable) is None
        # and model_fields_set contains the field
        if self.supplier_name is None and "supplier_name" in self.model_fields_set:
            _dict['supplierName'] = None

        # set to None if volume_discount_tiers (nullable) is None
        # and model_fields_set contains the field
        if self.volume_discount_tiers is None and "volume_discount_tiers" in self.model_fields_set:
            _dict['volumeDiscountTiers'] = None

        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of SupplierConditionCreate from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "currency": obj.get("currency"),
            "deliveryTerms": obj.get("deliveryTerms"),
            "earlyPaymentDiscountPercent": obj.get("earlyPaymentDiscountPercent"),
            "isDefault": obj.get("isDefault"),
            "minimumOrderValue": obj.get("minimumOrderValue"),
            "notes": obj.get("notes"),
            "paymentDueDays": obj.get("paymentDueDays"),
            "paymentTerms": obj.get("paymentTerms"),
            "supplierContactId": obj.get("supplierContactId"),
            "supplierName": obj.get("supplierName"),
            "volumeDiscountTiers": obj.get("volumeDiscountTiers")
        })
        return _obj


